### ISSUE TITLE
File permissions are not copied correctly to the sandbox

### ISSUE THREAD

**Issue by connorjclark** [stryker-mutator/stryker-js#1463]
Couldn't immediately find the name of the package for the babel transpiler from docs, so I googled it and got https://www.npmjs.com/package/stryker-babel-transpiler . But that doesn't work. Eventually found it is `@stryker-mutator/babel-transpiler`.

I guess all the packages moved to an org scope recently. Maybe deprecate the old ones + put a big disclaimer in the readme pointing to the correct package?

**Comment by Hoten** [comment]
Actually, I am have more issues, the above package didn't work.

Trying to run against `terser`.

```
10:54:39 (66028) ERROR StrykerCli an error occurred { Error: Could not inject "InitialTestExecutor". Inner error: Could not inject "TranspilerFacade". Inner error: Cannot load Transpiler plugin "babel". In fact, no Transpiler plugins were loaded. Did you forget to install it?
    at ClassProvider.injectClass (/Users/cjamcl/src/terser/node_modules/typed-inject/src/InjectorImpl.js:35:19)
    at ClassProvider.injectClass (/Users/cjamcl/src/terser/node_modules/typed-inject/src/InjectorImpl.js:95:22)
    at Stryker.<anonymous> (/Users/cjamcl/src/terser/node_modules/@stryker-mutator/core/src/Stryker.js:74:30)
    at step (/Users/cjamcl/src/terser/node_modules/tslib/tslib.js:133:27)
    at Object.next (/Users/cjamcl/src/terser/node_modules/tslib/tslib.js:114:57)
    at fulfilled (/Users/cjamcl/src/terser/node_modules/tslib/tslib.js:104:62)
    at <anonymous>
```

```
module.exports = function(config) {
  config.set({
    mutator: "javascript",
    packageManager: "npm",
    reporters: ["html", "clear-text", "progress"],
    testRunner: "command",
    transpilers: ["babel"],
    coverageAnalysis: "all"
  });
};
```

```
diff --git a/package.json b/package.json
index d05e452e..92f99546 100644
--- a/package.json
+++ b/package.json
@@ -35,6 +35,10 @@
     "source-map-support": "~0.5.9"
   },
   "devDependencies": {
+    "@stryker-mutator/babel-transpiler": "^1.1.1",
+    "@stryker-mutator/core": "^1.1.1",
+    "@stryker-mutator/html-reporter": "^1.1.1",
+    "@stryker-mutator/javascript-mutator": "^1.1.1",
     "acorn": "^6.0.4",
     "coveralls": "^3.0.2",
     "cross-env": "^5.2.0",

```

any idea what's wrong here?

**Comment by simondel** [comment]
Thanks for letting us know! It looks like our deprecation of the old package wasn't successful.

 You should see a similar warning like this on the npmjs page for `stryker-babel-transpiler`:
![image](https://user-images.githubusercontent.com/4221997/54811501-1cdd3380-4c89-11e9-8b2c-c1790e1a5067.png)
(taken from https://www.npmjs.com/package/stryker)

We'll fix this.

----
How do you run Stryker? Do you have a npm script in your package.json like this:
```
"scripts": {
    "test": "....",
    "stryker": "stryker run"
  },
```
or do you use the stryker-cli package?
```
stryker run
```
If you use the stryker-cli, could you check the version for me please?
```
npm list -g stryker-cli
```
If this is below 1.0.0, could you upgrade that to 1.0.0 as well?

**Comment by nicojs** [comment]
> It looks like our deprecation of the old package wasn't successful.

 Well... it was. I just decided to only deprecate the Stryker core package. I first wanted to see how it looked in the console, and it took a while to propagate. I will deprecate the rest when I find some time.

**Comment by simondel** [comment]
I have deprecated the old packages, so the only thing to do is make sure that @Hoten can run Stryker

**Comment by simondel** [comment]
@Hoten Are you still having issues?

**Comment by Hoten** [comment]
## Separate issue

Minor UI issue with the option `[optional] What kind transformations should be applied to your code?` in `init`. As a user, of course I don't fully read instructions (heh) and I hit "Enter" on `babel` with the intention of selecting Babel. This required me to manually install babel when getting the error in `run`. 

Mixing "Enter" with "yes, select this currently selected option" (most of the setup questions) and "yes, submit the options I've toggled" (the multi-select questions) is leads easily to this user error. Not sure of the best solution, but what about swapping Enter/Space bar for multi select questions?

## Running Stryker against [terser](https://github.com/terser-js/terser)

I actually don't need or want the `babel` transform for this :)

My config now:
```
module.exports = function(config) {
  config.set({
    mutator: "javascript",
    packageManager: "npm",
    reporters: ["html", "clear-text", "progress"],
    testRunner: "command",
    transpilers: [],
    coverageAnalysis: "off",
  });
};
```

`npm run test` does work, but I get this on `npx stryker run`:

```

```

There's a line in the npm debug log that gives me a hint:
```

```

**Comment by anthony-telljohann** [comment]
I'm experiencing the same file permissions issue with `@stryker-mutator/core@4.0.0`. In my scenario, I am intentionally coupling my node module with an executable with execute permissions. I'll look into what could be causing this bug and send a PR back if I figure it out.

**Comment by anthony-telljohann** [comment]
It looks like instead of copying files with`fs.copyFile`, `stryker` writes new files with the same name and contents with `fs.writeFile`. So to fix this, we'll need to figure out how to read the file permissions of every file so that we can then write new files with the same file permissions. Shouldn't be too difficult to do.

**Comment by victorperin** [comment]
I'm experiencing the same problem here too, I can help testing if needed.

About the solution i think @anthony-telljohann is in the right direction. I know you can use `fs.access` to get file permissions and `fs.chmod` to change it.

Infortunatly I do not know the stryker project enough to make a pull request, but I'll be trying to do it. But feel free to anyone do this.

**Comment by nicojs** [comment]
Dear stale bot, this issue is still present and should still be fixed in the future sweat\
