### ISSUE TITLE
A fallback for when `tree-kill` fails

### ISSUE THREAD

**Issue by sagar2427** [stryker-mutator/stryker-js#2448]
i down loaded example code from stryker.io , and i am start doing steps given ,to get the reports but whenever i am doing npm run stryker , i am getting error like above

**Comment by nicojs** [comment]
Ah yes. Couple of work arounds:

1. Install `git` and run `git init` in `D:\robobar-example-master`.
2. Install `git` and create a fresh clone: `git clone https://github.com/stryker-mutator/robobar-example.git` and use that instead.
3. Configure `files` inside the `stryker.conf.json`. You can use `"files": ["**/*", "!node_modules/**/*"]`

**Comment by sagar2427** [comment]
hey @nicojs   thanks for reply ,


based on our reply , i did same thing but still i am facing some issues related to my process id , PFB information for same thing
but i killed all the process but still i am facing issue, 


 ERROR StrykerCli an error occurred { Error: Command failed: taskkill /pid 14880 /T /F
'taskkill' is not recognized as an internal or external command,
operable program or batch file.


    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'taskkill /pid 14880 /T /F' }

**Comment by nicojs** [comment]
Did you install the dependencies?

```
npm install
```

**Comment by nicojs** [comment]
Ah, could you try to run `taskkill /?`, does that print the help for the `taskkill` command?

**Comment by sagar2427** [comment]
yup,
i did npm install for dependencies and i killed all the PIDs available in the task manager.
even i installed stryker global   npm install -g stryker-cli

but still i am getting same issue :(

**Comment by nicojs** [comment]
Hmm ok, so you are running on windows, yet `taskkill` isn't available. Could you verify this by running `taskkill /?`? 

Could you please provide more information about your system. What windows version are you running?

**Comment by sagar2427** [comment]
when ever i am running taskkill command its showing like 

D:\robobar-example-master>taskkill
'taskkill' is not recognized as an internal or external command,
operable program or batch file.

D:\robobar-example-master>taskkill /?
'taskkill' is not recognized as an internal or external command,
operable program or batch file.


windows version -- windows 10 pro 
                               64 bit OS, x65-based process

**Comment by nicojs** [comment]
For me, taskkill.exe lives in `C:\windows\system32`. Could you try to have a look there? If it's there, you might need to add `C:\windows\system32` to your PATH environment.

**Comment by nicojs** [comment]
I've also opened https://github.com/pkrumins/node-tree-kill/issues/34

**Comment by sagar2427** [comment]
Thanks @nicojs , after adding PATH environment , now able to run with out errors and i am coverage report also.

**Comment by nicojs** [comment]
Great! I've renamed the issue, we should implement a fallback for when `tree-kill` fails (maybe just use `process.kill`?).

**Comment by nicojs** [comment]
See #4577 for an example where a linux pipeline fails because of `tree-kill`. I think we should implement a fallback to normal `childProcess.kill` when tree-kill fails.

**Comment by BBoehm** [comment]
Hi @nicojs,
getting the same error:
```
Mutation testing  [                                                  ] 0% (elapsed: <1m, remaining: n/a) 5446/6838 Mutants tested (0 survived, 0 timed out)node:internal/errors:865
              ^

FEHLER: Nicht gefunden

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'taskkill /pid 1724 /T /F'
}
```

I already added  `C:\windows\system32` to my PATH variable and can use `taskkill /?`:
```
> taskkill /?

TASKKILL [/S System [/U Benutzername [/P [Kennwort]]]]
         { [/FI Filter] [/PID Prozess-ID | /IM Abbildname] } [/T] [/F]

...
```

Any ideas?
