### ISSUE TITLE
 TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by sagar2427** [stryker-mutator/stryker-js#2479]
i am trying to integrate stryker with my application but i facing below issue , after generated  stryker.conf.js

stryker.conf.js:

module.exports = function(config) {
    config.set({
        mutator: 'javascript',
        packageManager: 'npm',
        reporters: ['clear-text', 'progress'],
        testRunner: 'mocha',
        transpilers: [],
        testFramework: 'mocha',
      
        coverageAnalysis: 'perTest'
    });
};
  
after running stryker run command i getting below issue,

i installed
npm install
npm i -g stryker-cli
stryker init

TypeError: Cannot read property 'forEach' of undefined
    at module.exports (E:\sfcc\node_modules\mocha\lib\cli\collect-files.js:27:8)
    at MochaTestRunner.mocha6DiscoverFiles (E:sfcc\node_modules\@stryker-mutator\mocha-runner\src\MochaTestRunner.js:35:27)

**Comment by nicojs** [comment]
Hi @sagar2427 , apparently the mocha test runner is not able to find any files here? Please look at https://github.com/stryker-mutator/stryker/tree/master/packages/mocha-runner#readme for more info.

Just to be sure are you using mocha?

If you still have issues, please fill out the entire template, so we can help you better.

**Comment by rajatllm** [comment]
Hi @nicojs 

yes i am using Mocha is my test runner, Still i have issues , can you find below details,

Dependencies :

 "@stryker-mutator/core": "^2.0.0",
    "@stryker-mutator/html-reporter": "^2.0.0",
    "@stryker-mutator/javascript-mutator": "^2.0.0",
    "@stryker-mutator/mocha-framework": "^2.0.0",
    "@stryker-mutator/mocha-runner": "^2.0.0",


Stryker.cofg.js

module.exports = function(config) {
    config.set({
        mutator: 'javascript',
        mutate: ["**/**/cartridges/app_caridges_base/cartridge/scripts/helpers/storeHelpers"],
      packageManager: 'npm',
        reporters: ['clear-text', 'progress', 'html'],
        testRunner: 'mocha',
        transpilers: [],
        testFramework: 'mocha',
        coverageAnalysis: 'off',
       
        mochaOptions: {
        
             files:  '/test/unit/_base/scripts/helpers/storeHelpers.js'
            },
      
    });


Project structure:

 SFCC(main folder)
  |-other
  |-plugins 
  |-Myproject
    |-bin
    |-cartridges
    |-node moduels
    |-test
    |-Stryker.conf.js
    |



issue:

E:\myproject\sfcc\myproject>stryker run
10:55:15 (1208) INFO ConfigReader Using stryker.conf.js in the current working directory.
10:55:32 (1208) WARN InputFileResolver Globbing expression "**/myproject/cartridges/app_myproject_base/cartridge/scripts/helpers/*.js" did not result in any files.
10:55:33 (1208) WARN InputFileResolver No files marked to be mutated, Stryker will perform a dry-run without actually mutating anything. You can configure the `mutate` property in your stryker.conf.js file (or use `--mutate` via command line).
10:55:33 (1208) INFO InitialTestExecutor Starting initial test run. This may take a while.
10:55:41 (1208) ERROR StrykerCli an error occurred Error: TypeError: Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at module.exports (E:\myproject\sfcc\node_modules\mocha\lib\cli\collect-files.js:28:8)
    at MochaTestRunner.mocha6DiscoverFiles (E:\myproject\sfcc\myproject\node_modules\@stryker-mutator\mocha-runner\src\MochaTestRunner.js:35:27)
    at MochaTestRunner.init (E:\myproject\sfcc\myproject\node_modules\@stryker-mutator\mocha-runner\src\MochaTestRunner.js:22:39)
    at ChildProcessTestRunnerWorker.init (E:\myproject\sfcc\myproject\node_modules\@stryker-mutator\core\src\test-runner\ChildProcessTestRunnerWorker.js:15:45)
    at ChildProcessProxyWorker.doCall (E:\myproject\sfcc\myproject\node_modules\@stryker-mutator\core\src\child-proxy\ChildProcessProxyWorker.js:75:56)
    at resolve (E:\myproject\sfcc\myproject\node_modules\@stryker-mutator\core\src\child-proxy\ChildProcessProxyWorker.js:46:53)
    at new Promise (<anonymous>)
    at ChildProcessProxyWorker.handleMessage (E:\myproject\sfcc\myproject\node_modules\@stryker-mutator\core\src\child-proxy\ChildProcessProxyWorker.js:46:17)
    at process.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at ChildProcess.worker.on (E:\myproject\sfcc\myproject\node_modules\@stryker-mutator\core\src\child-proxy\ChildProcessProxy.js:133:68)
    at ChildProcess.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by sagar2427** [comment]
Hi @nicojs

yes i am using Mocha is my test runner, Still i have issues , can you find below details,

Dependencies :

"@stryker-mutator/core": "^2.0.0",
"@stryker-mutator/html-reporter": "^2.0.0",
"@stryker-mutator/javascript-mutator": "^2.0.0",
"@stryker-mutator/mocha-framework": "^2.0.0",
"@stryker-mutator/mocha-runner": "^2.0.0",

Stryker.cofg.js

module.exports = function(config) {
config.set({
mutator: 'javascript',
mutate: ["//cartridges/app_caridges_base/cartridge/scripts/helpers/storeHelpers"],
packageManager: 'npm',
reporters: ['clear-text', 'progress', 'html'],
testRunner: 'mocha',
transpilers: [],
testFramework: 'mocha',
coverageAnalysis: 'off',

    mochaOptions: {
    
         files:  '/test/unit/_base/scripts/helpers/storeHelpers.js'
        },
  
});
Project structure:

image

issue:

E:\myproject\sfcc\myproject>stryker run
10:55:15 (1208) INFO ConfigReader Using stryker.conf.js in the current working directory.
10:55:32 (1208) WARN InputFileResolver Globbing expression "**/myproject/cartridges/app_myproject_base/cartridge/scripts/helpers/*.js" did not result in any files.
10:55:33 (1208) WARN InputFileResolver No files marked to be mutated, Stryker will perform a dry-run without actually mutating anything. You can configure the mutate property in your stryker.conf.js file (or use --mutate via command line).
10:55:33 (1208) INFO InitialTestExecutor Starting initial test run. This may take a while.
10:55:41 (1208) ERROR StrykerCli an error occurred Error: TypeError: Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
at module.exports (E:\myproject\sfcc\node_modules\mocha\lib\cli\collect-files.js:28:8)
at MochaTestRunner.mocha6DiscoverFiles (E:\myproject\sfcc\myproject\node_modules@stryker-mutator\mocha-runner\src\MochaTestRunner.js:35:27)
at MochaTestRunner.init (E:\myproject\sfcc\myproject\node_modules@stryker-mutator\mocha-runner\src\MochaTestRunner.js:22:39)
at ChildProcessTestRunnerWorker.init (E:\myproject\sfcc\myproject\node_modules@stryker-mutator\core\src\test-runner\ChildProcessTestRunnerWorker.js:15:45)
at ChildProcessProxyWorker.doCall (E:\myproject\sfcc\myproject\node_modules@stryker-mutator\core\src\child-proxy\ChildProcessProxyWorker.js:75:56)
at resolve (E:\myproject\sfcc\myproject\node_modules@stryker-mutator\core\src\child-proxy\ChildProcessProxyWorker.js:46:53)
at new Promise ()
at ChildProcessProxyWorker.handleMessage (E:\myproject\sfcc\myproject\node_modules@stryker-mutator\core\src\child-proxy\ChildProcessProxyWorker.js:46:17)
at process.emit (events.js:198:13)
at emit (internal/child_process.js:832:12)
at ChildProcess.worker.on (E:\myproject\sfcc\myproject\node_modules@stryker-mutator\core\src\child-proxy\ChildProcessProxy.js:133:68)
at ChildProcess.emit (events.js:198:13)
at emit (internal/child_process.js:832:12)
at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by kmdrGroch** [comment]
2x version? try updating to 3x and check again. Also please send log file :)

**Comment by sagar2427** [comment]
Hi @kmdrGroch , i updated my version to 3x,now i am not getting my that issue but still i have facing issue like no tests are executed.  

 INFO ConfigReader Using stryker.conf.js
The @stryker-mutator/html-reporter package is a stub package. The html reporter is now included with @stryker-mutator/core. There is no need to have the @stryker-mutator/html-reporter package installed! Are you still using stryker v2? Then please upgrade stryker to at least 3.x using or downgrade this plugin to the latest 2.x release.
 WARN InputFileResolver Globbing expression "{src,lib}/**/?(*.)+(spec|test).js?(x)" did not result in any files.
 WARN InputFileResolver Globbing expression "{src,lib}/**/*+(Spec|Test).js?(x)" did not result in any files.
 INFO InputFileResolver Found 30 of 843 file(s) to be mutated.
INFO InitialTestExecutor Starting initial test run. This may take a while.
 WARN InitialTestExecutor No tests were executed. Stryker will exit prematurely. Please check your configuration.
INFO MutatorFacade 3216 Mutant(s) generated

Stryker.config.js

module.exports = function(config) {
 
    config.set({
        mutator: 'javascript',
   mutate: [" **/cartridges/app_myprojecg_base/cartridge/scripts/helpers/storeHelpers.js"],
      
        packageManager: 'npm',
        reporters: ['clear-text', 'progress', 'html'],
        testRunner: 'mocha',
        transpilers: [],
        testFramework: 'mocha',
        coverageAnalysis: 'off',
        symlinkNodeModules: false,fileLogLevel: 'trace',

        mochaOptions: {
            files: [ "./test/unit/**/*.js"],
  
            },
      
    });
};

Project structure:

![image](https://user-images.githubusercontent.com/62585882/94672728-4a517580-0333-11eb-93f2-48dd043f67a2.png)

**Comment by kmdrGroch** [comment]
so you have not added "files" option in config.
By default stryker takes files from: 
"{src,lib}//?(*.)+(spec|test).js?(x)"
"{src,lib}//*+(Spec|Test).js?(x)"
and it didnt find any.
Try adding files option :) https://github.com/stryker-mutator/stryker/blob/master/packages/core/README.md#files

**Comment by nicojs** [comment]
I think the issue is that your setting `files`. I think you want to use `spec`.

```js
mochaOptions: {
  spec: [ '/test/unit/_base/scripts/helpers/storeHelpers.js']
}
```

Note: `spec` should be an array.

https://github.com/stryker-mutator/stryker/tree/master/packages/mocha-runner#configuring

**Comment by sagar2427** [comment]
hi @nicojs ,

Thankyou @nicojs :)

after using spec array, now i am not able get issues but my case .need to do small change. like need to go back one more folder back.

mochaOptions: {
  spec: [ './test/unit/_base/scripts/helpers/storeHelpers.js']
}
