### ISSUE TITLE
Unexpected crash when not cleaning your stubs correctly

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-js#2492]
**Summary**

Whenever you forget to clean your stubs, this can have very strange consequences. For example:

```
$ npx stryker run
14:54:25 (19520) INFO ConfigReader Using stryker.conf.json
14:54:26 (19520) INFO InputFileResolver Found 28 of 71 file(s) to be mutated.
14:54:28 (19520) INFO Instrumenter Instrumented 28 source file(s) with 363 mutant(s)
14:54:28 (19520) INFO ConcurrencyTokenProvider Creating 1 test runner process(es).
14:54:29 (19520) INFO Sandbox Running build command "yarn build" in the sandbox at "/user/nicojs/backend-common/.stryker-tmp/sandbox1547662".
14:54:58 (19520) INFO DryRunExecutor Starting initial test run. This may take a while.
14:55:18 (19520) INFO DryRunExecutor Initial test run succeeded. Ran 87 tests in 53 seconds (net 534 ms, overhead 5535 ms).
Mutation testing  [                                                  ] 0% (elapsed: <1m, remaining: ~13m) 3/360 tested (0 survived, 0 timed out)14:55:26 (19520) WARN ChildProcessProxy Child process [pid 16432] exited unexpectedly with exit code 134 (without signal). Last part of stdout and stderr was:
        Debugger listening on ws://127.0.0.1:9229/91e56797-13e6-49b9-9e00-80e74706f520
        For help, see: https://nodejs.org/en/docs/inspector
        Debugger attached.
        stryker[16432]: c:\ws\src\node_contextify.cc:997: Assertion `args[0]->IsString()' failed.
         1: 00007FF6EFEA5EBF napi_wrap+114095
         2: 00007FF6EFE50B46 v8::base::CPU::has_sse+66998
         3: 00007FF6EFE50EC1 v8::base::CPU::has_sse+67889
         4: 00007FF6EFE59EE7 v8::base::CPU::has_sse+104791
         5: 00007FF6F061AAE0 v8::internal::Builtins::builtin_handle+323456
         6: 00007FF6F061A027 v8::internal::Builtins::builtin_handle+320711
         7: 00007FF6F061A368 v8::internal::Builtins::builtin_handle+321544
         8: 00007FF6F061A16E v8::internal::Builtins::builtin_handle+321038
         9: 00007FF6F0ABB4BD v8::internal::SetupIsolateDelegate::SetupHeap+546893
        10: 00007FF6F0A4036C v8::internal::SetupIsolateDelegate::SetupHeap+42748
        11: 00007FF6F0A4036C v8::internal::SetupIsolateDelegate::SetupHeap+42748
        12: 00007FF6F0A4036C v8::internal::SetupIsolateDelegate::SetupHeap+42748
        13: 00007FF6F0A4036C v8::internal::SetupIsolateDelegate::SetupHeap+42748
        14: 00007FF6F0A4036C v8::internal::SetupIsolateDelegate::SetupHeap+42748
        15: 0000031AB9126D4E
         ChildProcessCrashedError: Child process [pid 16432] exited unexpectedly with exit code 134 (without signal). Last part of stdout and stderr was:
        Debugger listening on ws://127.0.0.1:9229/91e56797-13e6-49b9-9e00-80e74706f520
        For help, see: https://nodejs.org/en/docs/inspector
        Debugger attached.
        stryker[16432]: c:\ws\src\node_contextify.cc:997: Assertion `args[0]->IsString()' failed.
         1: 00007FF6EFEA5EBF napi_wrap+114095
         2: 00007FF6EFE50B46 v8::base::CPU::has_sse+66998
         3: 00007FF6EFE50EC1 v8::base::CPU::has_sse+67889
         4: 00007FF6EFE59EE7 v8::base::CPU::has_sse+104791
         5: 00007FF6F061AAE0 v8::internal::Builtins::builtin_handle+323456
         6: 00007FF6F061A027 v8::internal::Builtins::builtin_handle+320711
         7: 00007FF6F061A368 v8::internal::Builtins::builtin_handle+321544
         8: 00007FF6F061A16E v8::internal::Builtins::builtin_handle+321038
         9: 00007FF6F0ABB4BD v8::internal::SetupIsolateDelegate::SetupHeap+546893
        10: 00007FF6F0A4036C v8::internal::SetupIsolateDelegate::SetupHeap+42748
        11: 00007FF6F0A4036C v8::internal::SetupIsolateDelegate::SetupHeap+42748
        12: 00007FF6F0A4036C v8::internal::SetupIsolateDelegate::SetupHeap+42748
        13: 00007FF6F0A4036C v8::internal::SetupIsolateDelegate::SetupHeap+42748
        14: 00007FF6F0A4036C v8::internal::SetupIsolateDelegate::SetupHeap+42748
        15: 0000031AB9126D4E

    at ChildProcessProxy.handleUnexpectedExit (C:\z\nn\poe\shared\backend-common\node_modules\@stryker-mutator\core\src\child-proxy\ChildProcessProxy.js:32:37)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  innerError: undefined,
  pid: 16432,
  exitCode: 134,
  signal: null
}
```

The reason for this error is this test hooks logic:

```js
export const mochaHooks = {
  beforeEach() {
    nock.cleanAll();
    sinon.restore();
  },
};
```

After changing the `beforeEach` to `afterEach` it works. 

The root cause is that we stub away `fs.readFileSync` in one of the tests. When nodejs loads files (`require`) it relies on `fs.readFileSync`, as you can see here:

![afbeelding](https://user-images.githubusercontent.com/1828233/94020331-19ad9100-fdb3-11ea-8220-8682c015655e.png)

Stryker handles it correctly (restart the runner and try the mutant again), but maybe we should try to help our users better? Maybe add this error to an FAQ?

**Stryker config**

```js
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "buildCommand": "yarn build",
  "testRunner": "mocha",
  "coverageAnalysis": "perTest",
  "mochaOptions": {
    "spec": ["dist/src/**/*.test.js", "dist/src/**/*.spec.js"]
  },
}

```

**Stryker environment**

```
| +-- @stryker-mutator/api@4.0.0-beta.8
| +-- @stryker-mutator/instrumenter@4.0.0-beta.8
| | +-- @stryker-mutator/api@4.0.0-beta.8 deduped
| | +-- @stryker-mutator/util@4.0.0-beta.8 deduped
| +-- @stryker-mutator/util@4.0.0-beta.8
+-- @stryker-mutator/mocha-runner@4.0.0-beta.8
 | +-- @stryker-mutator/api@4.0.0-beta.8 deduped
| +-- @stryker-mutator/util@4.0.0-beta.8 deduped
```

**Comment by Clete2** [comment]
For anyone who runs into this and cleaning up after each does not fix it, make sure that you are also `await`ing your test expectation:

```javascript
it('fails when receiving exception', async () => {
	const error: Error = { name: 'BadError', message: 'Oh no!' }
	quickSightMock.on(ListUsersCommand).rejects(error)

	await expect(quickSightUserManager.retrieveUsers()).rejects.toThrowError(error)
})
```

I struggled with this error for a long time and finally fixed it by adding the `await`. Thanks @nicojs for the original issue that helped me troubleshoot mock cleanup.
