### ISSUE TITLE
Support for the experimental syntax 'jsx' isn't currently enabled

### ISSUE THREAD

**Issue by jssolanki22** [stryker-mutator/stryker-js#2572]
**Summary**

Getting below error while running stryker. This is breaking only in case of stryker run

`Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.
    at Object._raise (D:\Work\GitHub\carwaleweb\Carwale\PWA\node_modules\@stryker-mutator\instrumenter\node_modules\@babel\parser\lib\index.js:766:17)
    at Object.raiseWithData (D:\Work\GitHub\carwaleweb\Carwale\PWA\node_modules\@stryker-mutator\instrumenter\node_modules\@babel\parser\lib\index.js:759:17)
    at Object.expectOnePlugin (D:\Work\GitHub\carwaleweb\Carwale\PWA\node_modules\@stryker-mutator\instrumenter\node_modules\@babel\parser\lib\index.js:8981:18)
    at Object.parseExprAtom (D:\Work\GitHub\carwaleweb\Carwale\PWA\node_modules\@stryker-mutator\instrumenter\node_modules\@babel\parser\lib\index.js:10276:22)
    at Object.parseExprAtom (D:\Work\GitHub\carwaleweb\Carwale\PWA\node_modules\@stryker-mutator\instrumenter\node_modules\@babel\parser\lib\index.js:7449:45)
    at Object.parseExprSubscripts (D:\Work\GitHub\carwaleweb\Carwale\PWA\node_modules\@stryker-mutator\instrumenter\node_modules\@babel\parser\lib\index.js:9844:23)       
    at Object.parseUpdate (D:\Work\GitHub\carwaleweb\Carwale\PWA\node_modules\@stryker-mutator\instrumenter\node_modules\@babel\parser\lib\index.js:9824:21)
    at Object.parseMaybeUnary (D:\Work\GitHub\carwaleweb\Carwale\PWA\node_modules\@stryker-mutator\instrumenter\node_modules\@babel\parser\lib\index.js:9813:17)
    at Object.parseExprOps (D:\Work\GitHub\carwaleweb\Carwale\PWA\node_modules\@stryker-mutator\instrumenter\node_modules\@babel\parser\lib\index.js:9683:23)
    at Object.parseMaybeConditional (D:\Work\GitHub\carwaleweb\Carwale\PWA\node_modules\@stryker-mutator\instrumenter\node_modules\@babel\parser\lib\index.js:9657:23)     
  loc: Position { line: 50, column: 4 },
  pos: 1261,
  missingPlugin: [ 'jsx', 'flow', 'typescript' ],
  code: 'BABEL_PARSE_ERROR' }`
**Stryker config**

```json
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "packageManager": "npm",
  "mutate": [
    "src/**/*.js?(x)",
    "!src/**/*@(.test|.spec|Spec).js?(x)"
  ],
  "mutator": "javascript",
  "reporters": [
    "html",
    "clear-text",
    "progress"
  ],
  "testRunner": "jest",
  "coverageAnalysis": "off"
}
```

**Test runner config**

**Stryker environment**

```
+-- @stryker-mutator/core@4.0.0
+-- @stryker-mutator/javascript-mutator@4.0.0
+-- @stryker-mutator/jest-runner@4.0.0
```

```
+-- jest@24.8.0
```

**Test runner environment**

```shell
"test": "jest --colors"
npm run test
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | v10.20.1
| npm              | 6.14.4
| Operating System | window 10

**Add stryker.log**
[stryker.log](https://github.com/stryker-mutator/stryker/files/5397084/stryker.log)

**Comment by nicojs** [comment]
What happens here, is that Stryker tries to parse your ".js" files, but can't because it is missing one or more babel syntax plugins. 

You can either configure a `.babelrc` file in the root of your project, or override the default syntax plugins that Stryker uses. (these are the default syntax plugins enabled by Stryker: https://github.com/stryker-mutator/stryker/blob/master/packages/instrumenter/src/parsers/js-parser.ts#L8-L32)

To do that, you can add `@babel/plugin-syntax-jsx` to your mutator plugins. See https://stryker-mutator.io/docs/stryker/configuration#mutator-mutatordescriptor

Like this:

```json
{
  "mutator": { 
    "plugins": ["@babel/plugin-syntax-jsx"]
  }
}
```

**Comment by bahmutov** [comment]
@nicojs using mutator plugins did not work

```
09:07:38 (25694) INFO ConfigReader Using stryker.conf.js
Mutator plugins are no longer needed in Stryker 4.0. Please remove "@stryker-mutator/javascript-mutator" from your devDependencies.
09:07:38 (25694) INFO InputFileResolver Found 1 of 20 file(s) to be mutated.
09:07:38 (25694) ERROR Stryker SyntaxError: /Users/gleb/git/cypress-mutation-example/src/index.js: Support for the experimental syntax 'jsx' isn't currently enabled (5:17):
```

Using `.babelrc` file with this contents DID work, thank you

```json
{
  "presets": [
    "@babel/preset-react"
  ]
}
```

My repo is https://github.com/bahmutov/cypress-mutation-example
