### ISSUE TITLE
Seemingly fragile process model

### ISSUE THREAD

**Issue by cbrunnkvist** [stryker-mutator/stryker-js#2778]
**stryker run fails for whatever reason, ends up in infinite loop with out-of-file-descriptors**

I'm trying to figure out the reason why stryker can't run properly with my react/webpack project (something related to babel(7) decorators, I guess) but it is requiring an increased amount of effort since each time I `stryker run`, it breaks my bash & terminal window like so:

```
bob@enola-gay:ui$ yarn stryker run
yarn run v1.22.10
warning package.json: No license field
$ /Users/bob/code/tttt/ffff-bbbb/ui/node_modules/.bin/stryker run
16:13:02 (55990) INFO ConfigReader Using stryker.conf.json
16:13:02 (55990) INFO InputFileResolver Found 2 of 245 file(s) to be mutated.
16:13:02 (55990) INFO Instrumenter Instrumented 2 source file(s) with 1 mutant(s)
16:13:03 (55990) INFO ConcurrencyTokenProvider Creating 7 test runner process(es).
16:13:03 (55990) INFO Sandbox Running build command "yarn build" in "/Users/bob/code/tttt/ffff-bbbb/ui/.stryker-tmp/sandbox7961777".
16:14:10 (55990) WARN Sandbox Could not symlink "/Users/bob/code/tttt/ffff-bbbb/ui/node_modules" in sandbox directory, it is already created in the sandbox. Please remove the node_modules from your sandbox files. Alternatively, set `symlinkNodeModules` to `false` to disable this warning.
16:14:11 (55990) INFO DryRunExecutor Starting initial test run. This may take a while.
Error: spawn pgrep EAGAIN
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Error: read ENOTCONN
    at tryReadStart (net.js:571:20)
    at Socket._read (net.js:582:5)
    at Socket.Readable.read (_stream_readable.js:474:10)
    at Socket.read (net.js:622:39)
    at new Socket (net.js:374:12)
    at Object.Socket (net.js:265:41)
    at createSocket (internal/child_process.js:313:14)
    at ChildProcess.spawn (internal/child_process.js:436:23)
    at spawn (child_process.js:548:9)
    at /Users/bob/code/tttt/ffff-bbbb/ui/node_modules/tree-kill/index.js:33:18
```
_goes on until ctrl-c, then degenerates into:_

```
-bash: fork: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable
```
_but continues to generate errors in the background, bash unusable at this point, `node` process must be killed from Activity Monitor_ 😞 

**Stryker config**

```json
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "_comment": "This config was generated using 'stryker init'. Please see the guide for more information: https://stryker-mutator.io/docs/stryker/guides/react",
  "testRunner": "jest",
  "mutate": ["src/components/core/*.js"],
  "reporters": ["progress", "clear-text", "html"],
  "coverageAnalysis": "off",
  "buildCommand": "yarn build", // just runs `webpack -p --env.something=x`
  "mutator": { "plugins": [] }, // tried this, but no significant difference
  "jest": {
    "projectType": "create-react-app"
  }
}
```

**Test runner config**

(in package.json)

```json
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.js",
      "!<rootDir>/src/{index,routesConfig}.js"
    ],
    "transform": {
      "^.+\\.js$": "babel-jest",
      "^.+\\.(css|scss|less)$": "jest-css-modules"
    },
    "testMatch": [
      "<rootDir>/test/**/?(*.)+(spec|test).js"
    ],
    "moduleNameMapper": {
      "^Components(.*)$": "<rootDir>/src/components/$1",
      "^Features(.*)$": "<rootDir>/src/features/$1",
      "^Src(.*)$": "<rootDir>/src/$1",
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/test/__mocks__/fileMock.js",
      "\\.(css|less)$": "<rootDir>/test/__mocks__/styleMock.js"
    },
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ]
  }
```
**Stryker environment**

`yarn list | grep stryker`

```
├─ @stryker-mutator/api@4.4.1
├─ @stryker-mutator/core@4.4.1
│  ├─ @stryker-mutator/api@4.4.1
│  ├─ @stryker-mutator/instrumenter@4.4.1
│  ├─ @stryker-mutator/util@4.4.1
├─ @stryker-mutator/instrumenter@4.4.1
│  ├─ @stryker-mutator/api@4.4.1
│  ├─ @stryker-mutator/util@4.4.1
├─ @stryker-mutator/jest-runner@4.4.1
│  ├─ @stryker-mutator/api@4.4.1
│  ├─ @stryker-mutator/util@4.4.1
├─ @stryker-mutator/util@4.4.1
```

```
+-- jest@26.6.0
```

**Test runner environment**

```shell
jest
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 14.4.0
| npm              | 7.5.6
| Operating System | macOS 11.2

**Add stryker.log**

[stryker.log](https://github.com/stryker-mutator/stryker/files/6089405/stryker.log)

**Comment by cbrunnkvist** [comment]
Ideally everything should work out-of-the-box but I realize how difficult that is due to the number of permutations available regarding transpilers & transpiler plugins, testrunners, es-language features, etc etc. 

But I think we need to be able to get out of infinite loops either way, or detect spawning problems and exit early...

**Comment by nicojs** [comment]
Hmm interesting. Maybe it has something to do with sandboxing your application. Stryker creates a copy of your source code (`.stryker-tmp/sandbox1234567`) where it runs the actual mutation testing (and the `--buildCommand`). However sometimes the act of sandboxing renders the application unfitted for running tests. 

Could you please try again with [`--inPlace`](https://stryker-mutator.io/docs/stryker/configuration/#inplace-boolean) mode active? This will make Stryker run in place, instead of in the sandbox directory. 

> Ideally everything should work out-of-the-box but I realize how difficult that is due to the number of permutations available regarding transpilers & transpiler plugins, testrunners, es-language features, etc etc.

Yeah, that's the nature of JS development a.t.m. 🙄
