### ISSUE TITLE
Jest 27 - unable to run stryker

### ISSUE THREAD

**Issue by HonzaMac** [stryker-mutator/stryker-js#2923]
When I update to jest 27, I am able to run locally stryker, but I am not able to run it at Jenkins.

See log from Jenkins.

```
[2021-05-27T12:53:27.024Z] + npm run stryker
[2021-05-27T12:53:27.024Z] 
[2021-05-27T12:53:27.024Z] > @js-com/winston-logstash@1.0.9 stryker /opt/jenkins/workspace/TS_JS-COP_winston-logstash_PR-25
[2021-05-27T12:53:27.024Z] > stryker run
[2021-05-27T12:53:27.024Z] 
[2021-05-27T12:53:28.469Z] 12:53:28 (1061252) INFO ConfigReader Using stryker.conf.json
[2021-05-27T12:53:28.469Z] 12:53:28 (1061252) INFO BroadcastReporter Detected that current console does not support the "progress" reporter, downgrading to "progress-append-only" reporter
[2021-05-27T12:53:28.469Z] 12:53:28 (1061252) INFO InputFileResolver Found 2 of 24 file(s) to be mutated.
[2021-05-27T12:53:29.884Z] 12:53:29 (1061252) INFO Instrumenter Instrumented 2 source file(s) with 141 mutant(s)
[2021-05-27T12:53:30.141Z] 12:53:29 (1061252) INFO ConcurrencyTokenProvider Creating 7 test runner process(es).
[2021-05-27T12:53:31.520Z] 12:53:31 (1061252) INFO DryRunExecutor Starting initial test run (jest test runner with "perTest" coverage analysis). This may take a while.
[2021-05-27T12:53:33.429Z] 12:53:32 (1061252) ERROR DryRunExecutor One or more tests resulted in an error:
[2021-05-27T12:53:33.430Z] 	undefinedCannot read property 'getEnv' of undefined TypeError: Cannot read property 'getEnv' of undefined
[2021-05-27T12:53:33.430Z]     at Object.<anonymous> (/opt/jenkins/workspace/TS_JS-COP_winston-logstash_PR-25/node_modules/@stryker-mutator/jest-runner/src/jest-plugins/jasmine2-setup-coverage-analysis.ts:2:16)
[2021-05-27T12:53:33.430Z]     at Runtime._execModule (/opt/jenkins/workspace/TS_JS-COP_winston-logstash_PR-25/node_modules/jest-runtime/build/index.js:1394:24)
[2021-05-27T12:53:33.430Z]     at Runtime._loadModule (/opt/jenkins/workspace/TS_JS-COP_winston-logstash_PR-25/node_modules/jest-runtime/build/index.js:996:12)
[2021-05-27T12:53:33.430Z]     at Runtime.requireModule (/opt/jenkins/workspace/TS_JS-COP_winston-logstash_PR-25/node_modules/jest-runtime/build/index.js:828:12)
[2021-05-27T12:53:33.430Z]     at jestAdapter (/opt/jenkins/workspace/TS_JS-COP_winston-logstash_PR-25/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:70:15)
[2021-05-27T12:53:33.430Z]     at runTestInternal (/opt/jenkins/workspace/TS_JS-COP_winston-logstash_PR-25/node_modules/jest-runner/build/runTest.js:386:16)
[2021-05-27T12:53:33.430Z]     at runTest (/opt/jenkins/workspace/TS_JS-COP_winston-logstash_PR-25/node_modules/jest-runner/build/runTest.js:478:34)
[2021-05-27T12:53:33.430Z]     at TestRunner.runTests (/opt/jenkins/workspace/TS_JS-COP_winston-logstash_PR-25/node_modules/jest-runner/build/index.js:111:12)
[2021-05-27T12:53:33.430Z]     at TestScheduler.scheduleTests (/opt/jenkins/workspace/TS_JS-COP_winston-logstash_PR-25/node_modules/@jest/core/build/TestScheduler.js:347:13)
[2021-05-27T12:53:33.430Z]     at runJest (/opt/jenkins/workspace/TS_JS-COP_winston-logstash_PR-25/node_modules/@jest/core/build/runJest.js:387:19)
[2021-05-27T12:53:33.430Z] 12:53:32 (1061252) ERROR Stryker Unexpected error occurred while running Stryker Error: Something went wrong in the initial test run
[2021-05-27T12:53:33.430Z]     at DryRunExecutor.validateResultCompleted (/opt/jenkins/workspace/TS_JS-COP_winston-logstash_PR-25/node_modules/@stryker-mutator/core/dist/src/process/3-dry-run-executor.js:61:15)
[2021-05-27T12:53:33.430Z]     at DryRunExecutor.timeDryRun (/opt/jenkins/workspace/TS_JS-COP_winston-logstash_PR-25/node_modules/@stryker-mutator/core/dist/src/process/3-dry-run-executor.js:71:14)
[2021-05-27T12:53:33.430Z]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2021-05-27T12:53:33.430Z]     at async MergeMapSubscriber.project (/opt/jenkins/workspace/TS_JS-COP_winston-logstash_PR-25/node_modules/@stryker-mutator/core/dist/src/concurrent/pool.js:62:28)
[2021-05-27T12:53:33.430Z] 12:53:32 (1061252) INFO Stryker Trouble figuring out what went wrong? Try `npx stryker run --fileLogLevel trace --logLevel debug` to get some more info.
```

Stryker config:
```
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "packageManager": "npm",
  "reporters": [
    "html",
    "clear-text",
    "progress"
  ],
  "testRunner": "jest",
  "thresholds": {
    "high": 80,
    "low": 60,
    "break": 50
  }
}
```

Package.json
```
{
    "@stryker-mutator/core": "5.0.0",
    "@stryker-mutator/jest-runner": "5.0.0",
    "jest": "27.0.1",
    "stryker-cli": "1.0.1",
    "ts-jest": "27.0.1",
    "typescript": "4.2.2",
},
  "jest": {
    "preset": "ts-jest",
    "testEnvironment": "node",
    "testMatch": [
      "**/*.test.ts"
    ],
    "coverageDirectory": "coverage",
    "coverageReporters": [
      "text",
      "html",
      "cobertura"
    ]
  }
}
```

**Comment by HonzaMac** [comment]
It may be related to switch of [jest-jasmine2 -> jest-circus](https://jestjs.io/blog/2021/05/25/jest-27#flipping-defaults)

**Comment by nicojs** [comment]
Hi @HonzaMac thanks for opening this issue. 

Jest 27 is not yet supported, #2861 should fix that. Will have a look to see what the holdup is.

**Comment by nicojs** [comment]
Current workaround: configure `jest` in your package.json with 

```json
{
  "jest": {
    "testRunner": "jest-circus/runner"
  }
}
```

That should do the trick

**Comment by nicojs** [comment]
Yeah, the breaking changes in Jest 27 for Stryker are mostely the changed defaults. If you override your `testRunner` and `testEnvironment` Stryker should still work. 

I'm working on the implementation in #2861, should be merged and released later today.

**Comment by nicojs** [comment]
I've just released `@stryker-mutator/jest-runner@5.0.1`, please let me know if you have any issues.

**Comment by HonzaMac** [comment]
Thank you! You were so fast! I will try it next week.

**Comment by Hongbo-Miao** [comment]
Works great on Jest 27 now. Thanks!
