### ISSUE TITLE
Stryker initial test run times out

### ISSUE THREAD

**Issue by SDolnutu** [stryker-mutator/stryker-js#2969]
**Question**

Running simply "stryker run", mutations are being created and everything seems to run smoothly, until i receive the error that the dry run failed:

```
22:19:29 (12628) DEBUG JestTestRunner Running jest with --findRelatedTests flag. Set jest.enableFindRelatedTests to false to run all tests on every mutant.
22:24:17 (9652) DEBUG TimeoutDecorator Timeout expired, restarting the process and reporting timeout
22:24:19 (9652) DEBUG ChildProcessProxy Disposing of worker process 12952
22:24:21 (9652) DEBUG ChildProcessProxy Kill 12952
22:24:26 (9652) DEBUG ChildProcessProxy Started ChildProcessTestRunnerWorker in child process 20336
22:24:38 (9652) ERROR DryRunExecutor Initial test run timed out!
22:24:38 (9652) DEBUG Stryker Not removing the temp dir because an error occurred
22:24:38 (9652) ERROR Stryker Unexpected error occurred while running Stryker Error: Something went wrong in the initial test run
    at DryRunExecutor.validateResultCompleted (C:\Users\avalchev\IdeaProjects\projectr\node_modules\@stryker-mutator\core\dist\src\process\3-dry-run-executor.js:61:15)
    at DryRunExecutor.timeDryRun (C:\Users\avalchev\IdeaProjects\project\node_modules\@stryker-mutator\core\dist\src\process\3-dry-run-executor.js:71:14)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async C:\Users\avalchev\IdeaProjects\project\node_modules\@stryker-mutator\core\dist\src\concurrent\pool.js:62:28
```
Just keep in mind that i receive Set jest.enableFindRelatedTests to false when in my config its true. If i set it to false the debuger wil say Set jest.enableFindRelatedTests to true. So thats why i removed it all together
```
+-- @stryker-mutator/core@5.1.1
```

```
+-- jest@5.1.1
```

**Additional context**

```
/**
 * @type {import('@stryker-mutator/api/core').StrykerOptions}
 */
module.exports = {
  _comment:
     "This config was generated using 'stryker init'. Please see the guide for more information: https://stryker-mutator.io/docs/stryker-js/guides/angular",
  mutate: [
    "*/.ts",
    "!**/*.spec.ts",
    "!**/*test.ts"
  ],
  testRunner: "jest",
  "jest": {
    "projectType": "custom",
    "configFile": "jest.config.js",
    "config": {
      "testEnvironment": "jest-environment-jsdom-sixteen"
    }
  },
  tempDirName: "stryker-tmp",
  reporters: ["progress", "clear-text", "html"],
  concurrency: 4,
  concurrency_comment:
     "Recommended to use about half of your available cores when running stryker with angular",
  coverageAnalysis: "perTest",
};
```

**Comment by nicojs** [comment]
Hi @SDolnutu 👋

How long does it normally take for you to run jest? Is it more than 5 minutes? If so, please change the dry run timeout: https://stryker-mutator.io/docs/stryker-js/configuration/#dryruntimeoutminutes-number

**Comment by CaiqueCoelho** [comment]
Hey @SDolnutu @nicojs I'm getting the same error, you guys were able to fix that?

**Comment by nicojs** [comment]
@CaiqueCoelho How long does normal unit testing take for you without parallelization?
