### ISSUE TITLE
@stryker-mutator/typescript-checker tries to watch node_modules/fs/package.json when requiring fs

### ISSUE THREAD

**Issue by ChristianGrete0770** [stryker-mutator/stryker-js#3110]
**Summary**

`typescript-checker` tries and fails to watch Node.js internals (`fs` and `fs/promises`).

**Stryker config**

```json
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "checkers": [
    "typescript"
  ],
  "cleanTempDir": false,
  "coverageAnalysis": "perTest",
  "disableTypeChecks": "src/**/*.ts",
  "htmlReporter": {
    "baseDir": "reports/mutation"
  },
  "jest": {
    "configFile": "jest.config.js"
  },
  "jsonReporter": {
    "fileName": "reports/mutation.json"
  },
  "logLevel": "warn",
  "mutate": [
    "src/index.ts"
  ],
  "packageManager": "yarn",
  "reporters": [
    "dots"
  ],
  "tempDirName": "mutations",
  "testRunner": "jest",
  "tsconfigFile": "tsconfig.json"
}
```

**Test runner config**

```js
module.exports = {
  coverageDirectory: 'reports/coverage',
  coverageReporters: ['html', 'text-summary'],
  globals: {
    'ts-jest': {
      tsconfig: 'tsconfig.json',
    },
  },
  modulePathIgnorePatterns: [
    '<rootDir>/dist',
    '<rootDir>/mutations',
    '<rootDir>/reports',
  ],
  preset: 'ts-jest',
  testMatch: ['<rootDir>/src/__tests__/*.test.ts'],
  watchPlugins: ['jest-watch-typeahead/filename', 'jest-watch-typeahead/testname'],
}

```

**Stryker environment**

```
├── @stryker-mutator/core@5.4.0
├── @stryker-mutator/jest-runner@5.4.0
├── @stryker-mutator/typescript-checker@5.4.0
```

```
├── @types/jest@27.0.1
├── jest-watch-typeahead@0.6.4
├── jest@27.1.0
├── ts-jest@27.0.5
```

**Test runner environment**

```shell
jest
```

TSConfig:
```json
{
  "compilerOptions": {
    "allowJs": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "checkJs": true,
    "downlevelIteration": true,
    "importsNotUsedAsValues": "error",
    "isolatedModules": true,
    "lib": [
      "esnext"
    ],
    "newLine": "lf",
    "noEmit": true,
    "noEmitOnError": true,
    "noErrorTruncation": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitOverride": true,
    "noImplicitReturns": true,
    "noPropertyAccessFromIndexSignature": true,
    "noUncheckedIndexedAccess": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "resolveJsonModule": true,
    "useDefineForClassFields": true
  },
  "extends": "@tsconfig/node14/tsconfig.json",
  "include": [
    ".eslintrc.js",
    "jest.config.js",
    "src/**/*"
  ]
}
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 14.17.5
| npm              | 7.20.6
| Operating System | macOS 11.5.2

**Add stryker.log**

```
16:53:35 (42912) INFO ConfigReader Using stryker.conf.json
16:53:35 (42912) DEBUG BroadcastReporter Broadcasting to reporters ["dots"]
16:53:35 (42912) DEBUG ConfigReader Loading config ./stryker.conf.json
16:53:35 (42912) DEBUG ConfigReader Loaded config: {
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "checkers": [
    "typescript"
  ],
  "cleanTempDir": false,
  "coverageAnalysis": "perTest",
  "disableTypeChecks": "src/**/*.ts",
  "htmlReporter": {
    "baseDir": "reports/mutation"
  },
  "jest": {
    "configFile": "jest.config.js"
  },
  "jsonReporter": {
    "fileName": "reports/mutation.json"
  },
  "logLevel": "warn",
  "mutate": [
    "src/index.ts"
  ],
  "packageManager": "yarn",
  "reporters": [
    "dots"
  ],
  "tempDirName": "mutations",
  "testRunner": "jest",
  "tsconfigFile": "tsconfig.json",
  "allowConsoleColors": true,
  "maxTestRunnerReuse": 0,
  "commandRunner": {
    "command": "npm test"
  },
  "clearTextReporter": {
    "allowColor": true,
    "logTests": true,
    "maxTestsToLog": 3
  },
  "dashboard": {
    "baseUrl": "https://dashboard.stryker-mutator.io/api/reports",
    "reportType": "full"
  },
  "eventReporter": {
    "baseDir": "reports/mutation/events"
  },
  "ignorePatterns": [],
  "fileLogLevel": "trace",
  "inPlace": false,
  "maxConcurrentTestRunners": 9007199254740991,
  "mutator": {
    "plugins": null,
    "excludedMutations": []
  },
  "plugins": [
    "@stryker-mutator/*"
  ],
  "appendPlugins": [],
  "symlinkNodeModules": true,
  "testRunnerNodeArgs": [],
  "thresholds": {
    "high": 80,
    "low": 60,
    "break": null
  },
  "timeoutFactor": 1.5,
  "timeoutMS": 5000,
  "dryRunTimeoutMinutes": 5,
  "warnings": true,
  "disableBail": false,
  "configFile": "./stryker.conf.json"
}
16:53:35 (42912) DEBUG PluginLoader Loading @stryker-mutator/* from ./node_modules/@stryker-mutator
16:53:35 (42912) DEBUG PluginLoader Loading plugin "./node_modules/@stryker-mutator/instrumenter" (matched with expression @stryker-mutator/*)
16:53:35 (42912) DEBUG PluginLoader Loading plugin "./node_modules/@stryker-mutator/jest-runner" (matched with expression @stryker-mutator/*)
16:53:35 (42912) DEBUG PluginLoader Loading plugin "./node_modules/@stryker-mutator/typescript-checker" (matched with expression @stryker-mutator/*)
16:53:35 (42912) DEBUG PluginLoader Loading plugins ./node_modules/@stryker-mutator/instrumenter
16:53:35 (42912) DEBUG PluginLoader Loading plugins ./node_modules/@stryker-mutator/jest-runner
16:53:35 (42912) DEBUG PluginLoader Loading plugins ./node_modules/@stryker-mutator/typescript-checker
16:53:35 (42912) DEBUG PluginLoader Loading plugins ./node_modules/@stryker-mutator/core/dist/src/reporters/index.js
16:53:35 (42912) DEBUG buildSchemaWithPluginContributions Contributing 1 schemas from plugins to options validation.
16:53:35 (42912) INFO InputFileResolver Found 1 of 34 file(s) to be mutated.
16:53:35 (42912) DEBUG InputFileResolver All input files: [
  "./.eslintrc.js",
  "./.gitignore",
  "./.yarnrc",
  "./jest.config.js",
  "./package.json",
  "./src/__tests__/__snapshots__/index.test.ts.snap",
  "./src/__tests__/index.test.ts",
  "./src/index.ts",
  "./stryker.conf.json",
  "./tsconfig.json",
  "./yarn.lock"
]
16:53:35 (42912) DEBUG InputFileResolver Files to mutate: [
  "./src/index.ts"
]
16:53:35 (42912) DEBUG TemporaryDirectory Using temp directory "./mutations"
16:53:35 (42912) DEBUG Instrumenter Instrumenting 1 source files with mutants
16:53:36 (42912) DEBUG Instrumenter Instrumented src/index.ts (52 mutant(s))
16:53:36 (42912) INFO Instrumenter Instrumented 1 source file(s) with 52 mutant(s)
16:53:36 (42912) DEBUG TSConfigPreprocessor Rewriting file File {
  name: './tsconfig.json',
  _content: <Buffer 7b 0a 20 20 22 63 6f 6d 70 69 6c 65 72 4f 70 74 69 6f 6e 73 22 3a 20 7b 0a 20 20 20 20 22 61 6c 6c 6f 77 4a 73 22 3a 20 74 72 75 65 2c 0a 20 20 20 20 ... 780 more bytes>,
  _textContent: '{\n' +
    '  "compilerOptions": {\n' +
    '    "allowJs": true,\n' +
    '    "allowUnreachableCode": false,\n' +
    '    "allowUnusedLabels": false,\n' +
    '    "checkJs": true,\n' +
    '    "downlevelIteration": true,\n' +
    '    "importsNotUsedAsValues": "error",\n' +
    '    "isolatedModules": true,\n' +
    '    "lib": [\n' +
    '      "esnext"\n' +
    '    ],\n' +
    '    "newLine": "lf",\n' +
    '    "noEmit": true,\n' +
    '    "noEmitOnError": true,\n' +
    '    "noErrorTruncation": true,\n' +
    '    "noFallthroughCasesInSwitch": true,\n' +
    '    "noImplicitOverride": true,\n' +
    '    "noImplicitReturns": true,\n' +
    '    "noPropertyAccessFromIndexSignature": true,\n' +
    '    "noUncheckedIndexedAccess": true,\n' +
    '    "noUnusedLocals": true,\n' +
    '    "noUnusedParameters": true,\n' +
    '    "resolveJsonModule": true,\n' +
    '    "useDefineForClassFields": true\n' +
    '  },\n' +
    '  "extends": "@tsconfig/node14/tsconfig.json",\n' +
    '  "include": [\n' +
    '    ".eslintrc.js",\n' +
    '    "jest.config.js",\n' +
    '    "src/**/*"\n' +
    '  ]\n' +
    '}'
}
16:53:36 (42912) INFO ConcurrencyTokenProvider Creating 6 checker process(es) and 5 test runner process(es).
16:53:36 (42912) DEBUG ChildProcessProxy Started CheckerWorker in child process 42913
16:53:36 (42912) DEBUG ChildProcessProxy Started CheckerWorker in child process 42914
16:53:37 (42912) DEBUG Stryker Not removing the temp dir because an error occurred
16:53:37 (42912) ERROR Stryker Unexpected error occurred while running Stryker Error: Error: An error occurred during initialization of the "typescript" checker. Inner error: Error: Cannot find file ./node_modules/fs/package.json for watching
Error: Cannot find file ./node_modules/fs/package.json for watching
    at HybridFileSystem.watchFile (./node_modules/@stryker-mutator/typescript-checker/dist/src/fs/hybrid-file-system.js:47:19)
    at Object.watchFile (./node_modules/@stryker-mutator/typescript-checker/dist/src/typescript-checker.js:72:25)
    at watchFile (./node_modules/typescript/lib/typescript.js:110912:90)
    at Object.watchFile (./node_modules/typescript/lib/typescript.js:110938:34)
    at createNewValue (./node_modules/typescript/lib/typescript.js:120123:68)
    at ./node_modules/typescript/lib/typescript.js:19255:30
    at Map.forEach (<anonymous>)
    at Object.mutateMap (./node_modules/typescript/lib/typescript.js:19252:16)
    at watchPackageJsonFiles (./node_modules/typescript/lib/typescript.js:120122:12)
    at startWatching (./node_modules/typescript/lib/typescript.js:120144:17)
Error: An error occurred during initialization of the "typescript" checker. Inner error: Error: Cannot find file ./node_modules/fs/package.json for watching
Error: Cannot find file ./node_modules/fs/package.json for watching
    at HybridFileSystem.watchFile (./node_modules/@stryker-mutator/typescript-checker/dist/src/fs/hybrid-file-system.js:47:19)
    at Object.watchFile (./node_modules/@stryker-mutator/typescript-checker/dist/src/typescript-checker.js:72:25)
    at watchFile (./node_modules/typescript/lib/typescript.js:110912:90)
    at Object.watchFile (./node_modules/typescript/lib/typescript.js:110938:34)
    at createNewValue (./node_modules/typescript/lib/typescript.js:120123:68)
    at ./node_modules/typescript/lib/typescript.js:19255:30
    at Map.forEach (<anonymous>)
    at Object.mutateMap (./node_modules/typescript/lib/typescript.js:19252:16)
    at watchPackageJsonFiles (./node_modules/typescript/lib/typescript.js:120122:12)
    at startWatching (./node_modules/typescript/lib/typescript.js:120144:17)
    at CheckerWorker.init (./node_modules/@stryker-mutator/core/dist/src/checker/checker-worker.js:20:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ChildProcessProxyWorker.handleCall (./node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy-worker.js:66:28)
    at ChildProcess.<anonymous> (./node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:135:68)
    at ChildProcess.emit (events.js:400:28)
    at emit (internal/child_process.js:910:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
16:53:37 (42912) DEBUG ChildProcessProxy Disposing of worker process 42913
16:53:37 (42912) DEBUG ChildProcessProxy Disposing of worker process 42914
16:53:36 (42913) DEBUG PluginLoader Loading @stryker-mutator/* from ./node_modules/@stryker-mutator
16:53:36 (42913) DEBUG PluginLoader Loading plugin "./node_modules/@stryker-mutator/instrumenter" (matched with expression @stryker-mutator/*)
16:53:36 (42913) DEBUG PluginLoader Loading plugin "./node_modules/@stryker-mutator/jest-runner" (matched with expression @stryker-mutator/*)
16:53:36 (42913) DEBUG PluginLoader Loading plugin "./node_modules/@stryker-mutator/typescript-checker" (matched with expression @stryker-mutator/*)
16:53:36 (42913) DEBUG PluginLoader Loading plugins ./node_modules/@stryker-mutator/instrumenter
16:53:36 (42913) DEBUG PluginLoader Loading plugins ./node_modules/@stryker-mutator/jest-runner
16:53:36 (42913) DEBUG PluginLoader Loading plugins ./node_modules/@stryker-mutator/typescript-checker
16:53:36 (42913) DEBUG PluginLoader Loading plugins ./node_modules/@stryker-mutator/core/dist/src/reporters/index.js
16:53:37 (42913) TRACE TypescriptChecker summary message TS6194: Found 0 errors. Watching for file changes.

16:53:37 (42913) TRACE TypescriptChecker.HybridFileSystem Registering watcher for file "./tsconfig.json"
16:53:37 (42913) TRACE TypescriptChecker.HybridFileSystem Registering watcher for file "./node_modules/@tsconfig/node14/tsconfig.json"
16:53:37 (42913) TRACE TypescriptChecker.HybridFileSystem Registering watcher for file "./.eslintrc.js"
16:53:37 (42913) TRACE TypescriptChecker.HybridFileSystem Registering watcher for file "./jest.config.js"
16:53:37 (42913) TRACE TypescriptChecker.HybridFileSystem Registering watcher for file "./src/index.ts"
16:53:37 (42913) TRACE TypescriptChecker.HybridFileSystem Registering watcher for file "./src/__tests__/index.test.ts"
16:53:37 (42912) DEBUG ChildProcessProxy Kill 42913
16:53:36 (42914) DEBUG PluginLoader Loading @stryker-mutator/* from ./node_modules/@stryker-mutator
16:53:36 (42914) DEBUG PluginLoader Loading plugin "./node_modules/@stryker-mutator/instrumenter" (matched with expression @stryker-mutator/*)
16:53:36 (42914) DEBUG PluginLoader Loading plugin "./node_modules/@stryker-mutator/jest-runner" (matched with expression @stryker-mutator/*)
16:53:36 (42914) DEBUG PluginLoader Loading plugin "./node_modules/@stryker-mutator/typescript-checker" (matched with expression @stryker-mutator/*)
16:53:36 (42914) DEBUG PluginLoader Loading plugins ./node_modules/@stryker-mutator/instrumenter
16:53:36 (42914) DEBUG PluginLoader Loading plugins ./node_modules/@stryker-mutator/jest-runner
16:53:36 (42914) DEBUG PluginLoader Loading plugins ./node_modules/@stryker-mutator/typescript-checker
16:53:36 (42914) DEBUG PluginLoader Loading plugins ./node_modules/@stryker-mutator/core/dist/src/reporters/index.js
16:53:37 (42914) TRACE TypescriptChecker summary message TS6194: Found 0 errors. Watching for file changes.

16:53:37 (42914) TRACE TypescriptChecker.HybridFileSystem Registering watcher for file "./tsconfig.json"
16:53:37 (42914) TRACE TypescriptChecker.HybridFileSystem Registering watcher for file "./node_modules/@tsconfig/node14/tsconfig.json"
16:53:37 (42914) TRACE TypescriptChecker.HybridFileSystem Registering watcher for file "./.eslintrc.js"
16:53:37 (42914) TRACE TypescriptChecker.HybridFileSystem Registering watcher for file "./jest.config.js"
16:53:37 (42914) TRACE TypescriptChecker.HybridFileSystem Registering watcher for file "./src/index.ts"
16:53:37 (42914) TRACE TypescriptChecker.HybridFileSystem Registering watcher for file "./src/__tests__/index.test.ts"
16:53:37 (42912) DEBUG ChildProcessProxy Kill 42914

```

`./.eslintrc.js` requires `fs` and is included in `tsconfig.json` for typechecking and linting. The absolute path is replaced with `.` and some files have been removed from the logs for privacy reasons.

**Comment by nicojs** [comment]
Thanks for reporting this issue. I'll try to take a look in about a month or so (I'm going on vacation)

As a workaround, you could try to create a `tsconfig.stryker.json` file where you extend from the original, but alter the `files` to exclude the eslint config file and configure that file in stryker conf file.

**Comment by ericcornelissen** [comment]
I'm experiencing a similar problem in [a project of mine](https://github.com/ericcornelissen/svgo-action) after I recently updated all my dependencies, except for me it's complaining about [`@actions/github`](https://www.npmjs.com/package/@actions/github)'s `package.json` instead of `fs`.

First, I tried to switch back to Styker (core & typescript-checker) v5.2.3 but that didn't fix it. After some trail and error I found that everything works fine again when I revert TypeScript itself back to `4.3.5` from `4.4.2` (haven't tried any version in between yet). @ChristianGrete0770, could you confirm if the same is true on your end?

**Comment by ChristianGrete0770** [comment]
@nicojs I have already tried out to provide a specific tsconfig file for stryker, which indeed fixed the errors for `fs` and `fs/promise` but instead complained about `@types/babel__core`... Have a nice vacation, btw. 😉

@ericcornelissen I can confirm that downgrading typescript from `^4.4.2` to `~4.3.5` fixes the issue on my site.

**Comment by nicojs** [comment]
Ah zo it's most probably a bug that's introduced with TS 4.4 that didn't appear in our e2e tests. Great find, should be a pretty straightforward fix.

**Comment by mscharley** [comment]
I'm also having this issue in a library with no third-party dependencies - in my case it's failing on trying to find a package.json inside my own library code: mscharley/generic-type-guard#369

```
05:33:38 (121) ERROR Stryker Unexpected error occurred while running Stryker Error: Error: An error occurred during initialization of the "typescript" checker. Inner error: Error: Cannot find file /mnt/ramdisk/dist/combinators/package.json for watching
Error: Cannot find file /mnt/ramdisk/dist/combinators/package.json for watching
    at HybridFileSystem.watchFile (/mnt/ramdisk/node_modules/@stryker-mutator/typescript-checker/dist/src/fs/hybrid-file-system.js:47:19)
    at Object.watchFile (/mnt/ramdisk/node_modules/@stryker-mutator/typescript-checker/dist/src/typescript-checker.js:72:25)
    at watchFile (/mnt/ramdisk/node_modules/typescript/lib/typescript.js:110912:90)
    at Object.watchFile (/mnt/ramdisk/node_modules/typescript/lib/typescript.js:110938:34)
    at createNewValue (/mnt/ramdisk/node_modules/typescript/lib/typescript.js:120127:68)
    at /mnt/ramdisk/node_modules/typescript/lib/typescript.js:19255:30
    at Map.forEach (<anonymous>)
    at Object.mutateMap (/mnt/ramdisk/node_modules/typescript/lib/typescript.js:19252:16)
    at watchPackageJsonFiles (/mnt/ramdisk/node_modules/typescript/lib/typescript.js:120126:12)
    at startWatching (/mnt/ramdisk/node_modules/typescript/lib/typescript.js:120148:17)
Error: An error occurred during initialization of the "typescript" checker. Inner error: Error: Cannot find file /mnt/ramdisk/dist/combinators/package.json for watching
Error: Cannot find file /mnt/ramdisk/dist/combinators/package.json for watching
    at HybridFileSystem.watchFile (/mnt/ramdisk/node_modules/@stryker-mutator/typescript-checker/dist/src/fs/hybrid-file-system.js:47:19)
    at Object.watchFile (/mnt/ramdisk/node_modules/@stryker-mutator/typescript-checker/dist/src/typescript-checker.js:72:25)
    at watchFile (/mnt/ramdisk/node_modules/typescript/lib/typescript.js:110912:90)
    at Object.watchFile (/mnt/ramdisk/node_modules/typescript/lib/typescript.js:110938:34)
    at createNewValue (/mnt/ramdisk/node_modules/typescript/lib/typescript.js:120127:68)
    at /mnt/ramdisk/node_modules/typescript/lib/typescript.js:19255:30
    at Map.forEach (<anonymous>)
    at Object.mutateMap (/mnt/ramdisk/node_modules/typescript/lib/typescript.js:19252:16)
    at watchPackageJsonFiles (/mnt/ramdisk/node_modules/typescript/lib/typescript.js:120126:12)
    at startWatching (/mnt/ramdisk/node_modules/typescript/lib/typescript.js:120148:17)
    at CheckerWorker.init (/mnt/ramdisk/node_modules/@stryker-mutator/core/dist/src/checker/checker-worker.js:20:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ChildProcessProxyWorker.handleCall (/mnt/ramdisk/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy-worker.js:66:28)
    at ChildProcess.<anonymous> (/mnt/ramdisk/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:135:68)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

Based on the paths involved, it may be an issue when trying to import a folder, eg. I changed my imports for the combinators folder like this:

```typescript
// from this:
import * as c from './combinators';
// to this:
import * as c from './combinators/index';
```

And that cleared up the error related to that folder and threw them into one of the testing packages folders instead.
