### ISSUE TITLE
typescript-checker does not support TypeScript 4.4

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-js#3176]
**Summary**

Running Stryker with the typescript-checker results in an error as of TypeScript 4.4. Example:

```
3:43:10 (25475) INFO ConcurrencyTokenProvider Creating 4 checker process(es) and 3 test runner process(es).
13:43:13 (25475) ERROR Stryker Unexpected error occurred while running Stryker Error: Error: An error occurred during initialization of the "typescript" checker. Inner error: Error: Cannot find file /home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/react/jsx-runtime/package.json for watching
Error: Cannot find file /home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/react/jsx-runtime/package.json for watching
    at HybridFileSystem.watchFile (/home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/@stryker-mutator/typescript-checker/dist/src/fs/hybrid-file-system.js:47:19)
    at Object.watchFile (/home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/@stryker-mutator/typescript-checker/dist/src/typescript-checker.js:72:25)
    at watchFile (/home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/typescript/lib/typescript.js:110912:90)
    at Object.watchFile (/home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/typescript/lib/typescript.js:110938:34)
    at createNewValue (/home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/typescript/lib/typescript.js:120127:68)
    at /home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/typescript/lib/typescript.js:19255:30
    at Map.forEach (<anonymous>)
    at Object.mutateMap (/home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/typescript/lib/typescript.js:19252:16)
    at watchPackageJsonFiles (/home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/typescript/lib/typescript.js:120126:12)
    at startWatching (/home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/typescript/lib/typescript.js:120148:17)
Error: An error occurred during initialization of the "typescript" checker. Inner error: Error: Cannot find file /home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/react/jsx-runtime/package.json for watching
Error: Cannot find file /home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/react/jsx-runtime/package.json for watching
    at HybridFileSystem.watchFile (/home/nicojs/github/tmp/stryker-js-create-react-app-typescript/node_modules/@stryker-mutator/typescript-checker/dist/src/fs/hybrid-file-system.js:47:19)
```

**Stryker config**

```json
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "_comment": "This config was generated using 'stryker init'. Please see the guide for more information: https://stryker-mutator.io/docs/stryker-js/guides/react",
  "testRunner": "jest",
  "reporters": [
    "progress",
    "clear-text",
    "html"
  ],
  "checkers": ["typescript"],
  "tsconfigFile": "tsconfig.json",
  "coverageAnalysis": "off",
  "jest": {
    "projectType": "create-react-app"
  }
}
```

**Test runner config**

n/a

**Reproduction**

```shell
npx create-react-app stryker-js-create-react-app-typescript --template typescript
yarn add --dev @stryker-mutator/core @stryker-mutator/typescript-checker
npx stryker init
# Choose create-react-app
npx stryker run
# 💥
```

**Comment by nicojs** [comment]
Released in v5.4.1
