### ISSUE TITLE
expressionMutantPlacer could not place mutants with type(s): "StringLiteral"

### ISSUE THREAD

**Issue by bsssshhhhhhh** [stryker-mutator/stryker-js#3253]
I'm getting an error trying to run stryker mutator against my code.

```
$ stryker --version
5.4.1
```

Repro case here:
https://github.com/bsssshhhhhhh/composables/tree/stryker

```
$ stryker run
20:57:51 (21556) INFO ConfigReader Using stryker.conf.json
20:57:51 (21556) INFO InputFileResolver Found 3 of 155 file(s) to be mutated.
20:57:52 (21556) ERROR Stryker Unexpected error occurred while running Stryker SyntaxError: src\lib\breakpoints\breakpoints.ts:46:58 expressionMutantPlacer could not place mutants with type(s): "StringLiteral". Either remove this file from the list of files to be mutated, or exclude the mutator (using mutator.excludedMutations). Please report this issue at https://github.com/stryker-mutator/stryker-js/issues/new?assignees=&labels=%F0%9F%90%9B+Bug&template=bug_report.md&title=expressionMutantPlacer%20could%20not%20place%20mutants%20with%20type(s)%3A%20%22StringLiteral%22. Original error: TypeError: Property literal of TSLiteralType expected node to be of a type ["NumericLiteral","StringLiteral","BooleanLiteral","BigIntLiteral"] but instead got "ConditionalExpression"
    at validate (@bsssshhhhhhh\composables\node_modules\@babel\types\lib\definitions\utils.js:130:11)
    at Object.validator [as validate] (@bsssshhhhhhh\composables\node_modules\@babel\types\lib\definitions\typescript.js:284:13)
    at validateField (@bsssshhhhhhh\composables\node_modules\@babel\types\lib\validators\validate.js:24:9)
    at validate (@bsssshhhhhhh\composables\node_modules\@babel\types\lib\validators\validate.js:17:3)
    at NodePath._replaceWith (@bsssshhhhhhh\composables\node_modules\@babel\traverse\lib\path\replacement.js:170:5)
    at NodePath.replaceWith (@bsssshhhhhhh\composables\node_modules\@babel\traverse\lib\path\replacement.js:152:8)
    at Object.place (@bsssshhhhhhh\composables\node_modules\@stryker-mutator\instrumenter\dist\src\mutant-placers\expression-mutant-placer.js:102:14)
    at placeMutantsIfNeeded (@bsssshhhhhhh\composables\node_modules\@stryker-mutator\instrumenter\dist\src\transformers\babel-transformer.js:109:41)
    at exit (@bsssshhhhhhh\composables\node_modules\@stryker-mutator\instrumenter\dist\src\transformers\babel-transformer.js:54:13)
    at NodePath._call (@bsssshhhhhhh\composables\node_modules\@babel\traverse\lib\path\context.js:53:20)
  44 | },
  45 |   BreakpointNames extends string & keyof BreakpointDef = string & keyof BreakpointDef,
> 46 |   IsBreakpointRefNames extends string | number | symbol = `is${PascalCase<BreakpointNames>}`,
     |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  47 |   IsAboveBreakpointRefNames extends string | number | symbol = `isAbove${PascalCase<BreakpointNames>}`,
  48 |   IsBelowBreakpointRefNames extends string | number | symbol = `isBelow${PascalCase<BreakpointNames>}`
  49 | >(breakpoints: BreakpointDef, size: Ref<number> = useWindowSize().width) {
    at File.buildCodeFrameError @bsssshhhhhhh\composables\node_modules\@babel\core\lib\transformation\file\file.js:249:12)
    at NodePath.buildCodeFrameError (@bsssshhhhhhh\composables\node_modules\@babel\traverse\lib\path\index.js:139:21)
    at throwPlacementError (@bsssshhhhhhh\composables\node_modules\@stryker-mutator\instrumenter\dist\src\mutant-placers\throw-placement-error.js:18:31)
    at placeMutantsIfNeeded (@bsssshhhhhhh\composables\node_modules\@stryker-mutator\instrumenter\dist\src\transformers\babel-transformer.js:113:58)
    at exit (@bsssshhhhhhh\composables\node_modules\@stryker-mutator\instrumenter\dist\src\transformers\babel-transformer.js:54:13)
    at NodePath._call (@bsssshhhhhhh\composables\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (@bsssshhhhhhh\composables\node_modules\@babel\traverse\lib\path\context.js:36:14)
    at NodePath.visit (@bsssshhhhhhh\composables\node_modules\@babel\traverse\lib\path\context.js:99:8)
    at TraversalContext.visitQueue (@bsssshhhhhhh\composables\node_modules\@babel\traverse\lib\context.js:103:16)
    at TraversalContext.visitSingle (@bsssshhhhhhh\composables\node_modules\@babel\traverse\lib\context.js:77:19)
20:57:52 (21556) INFO Stryker Trouble figuring out what went wrong? Try `npx stryker run --fileLogLevel trace --logLevel debug` to get some more info.
```

**Comment by nicojs** [comment]
Thanks for opening this issue. It seems that Stryker is trying to mutate TypeScript template literal types. That shouldn't happen. Thanks for the reproduction repo, seems like a straightforward fix. Will try to do it before next release and I am hoping to get that out of the way by the end of the week.
