### ISSUE TITLE
BABEL_TRANSFORM_ERROR: The second argument of `jest.mock` must be an inline function

### ISSUE THREAD

**Issue by suzanicris** [stryker-mutator/stryker-js#3304]
**Question**
What should I do to run the tests? 

**Stryker environment**

```
├─┬ @stryker-mutator/core@5.5.1
│ ├─┬ @stryker-mutator/api@5.5.1
│ ├─┬ @stryker-mutator/instrumenter@5.5.1
│ │ ├── @stryker-mutator/api@5.5.1 deduped
│ │ ├── @stryker-mutator/util@5.5.1 deduped
│ ├─┬ @stryker-mutator/util@5.5.1
├─┬ @stryker-mutator/jest-runner@5.5.1
│ ├── @stryker-mutator/api@5.5.1 deduped
│ ├── @stryker-mutator/util@5.5.1 deduped
```

```
+-- jest@26.0.1
+--@testing-library/jest-dom@4.2.4
+--@testing-library/react@9.5.0
```

**Additional context**

stryker.conf.js
```
module.exports = {
	packageManager: 'npm',
	reporters: ['html', 'clear-text', 'progress'],
	testRunner: 'jest',
	coverageAnalysis: 'off',
	mutate: ['components/**/*.js'],
	mutator: {
		plugins: [],
	},
	jest: {
		projectType: 'custom',
		configFile: 'jest.config.js',
	},
};
```

Error:
![image](https://user-images.githubusercontent.com/31145790/145272328-bee4b90d-7495-4548-9c42-452adb82ab93.png)

The original code:
![image](https://user-images.githubusercontent.com/31145790/145272447-1570f479-7464-48ae-96ca-b424fc81fb71.png)

**Comment by nicojs** [comment]
You shouldn't be mutating your test code.

```diff
module.exports = {
	packageManager: 'npm',
	reporters: ['html', 'clear-text', 'progress'],
	testRunner: 'jest',
	coverageAnalysis: 'off',
-	mutate: ['components/**/*.js'],
+mutate: ['components/**/*.js', '!components/**/*.spec.js'],
	mutator: {
		plugins: [],
	},
	jest: {
		projectType: 'custom',
		configFile: 'jest.config.js',
	},
};
```

**Comment by suzanicris** [comment]
It works!

I tried set "perTest", but:
```
Require stack:
- /home/scristina/workspace/crm-moses-web/node_modules/@stryker-mutator/util/dist/src/require-resolve.js
- /home/scristina/workspace/crm-moses-web/node_modules/@stryker-mutator/util/dist/src/index.js
- /home/scristina/workspace/crm-moses-web/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy-worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.resolve (internal/modules/cjs/helpers.js:99:19)
    at requireResolve (/home/scristina/workspace/crm-moses-web/node_modules/@stryker-mutator/util/dist/src/require-resolve.js:10:28)
    at new jestEnvironmentGeneric (/home/scristina/workspace/crm-moses-web/node_modules/@stryker-mutator/jest-runner/dist/src/jest-plugins/jest-environment-generic.js:6:59)
    at runTestInternal (/home/scristina/workspace/crm-moses-web/node_modules/jest-runner/build/runTest.js:262:23)
    at runTest (/home/scristina/workspace/crm-moses-web/node_modules/jest-runner/build/runTest.js:472:40)
    at /home/scristina/workspace/crm-moses-web/node_modules/jest-runner/build/index.js:154:45, MODULE_NOT_FOUND Cannot find module 'enzyme'
```

**Comment by nicojs** [comment]
Wow! That is super weird.

Could you please create another issue for that with the details? 😇

**Comment by suzanicris** [comment]
Sure!! Created #3307 

Thank you so much!
