### ISSUE TITLE
expressionMutantPlacer could not place mutants with type

### ISSUE THREAD

**Issue by lordphnx** [stryker-mutator/stryker-js#3475]
**Summary**

Did an out-of-the-box run of Stryker

**Stryker config**

```json
{
	"$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
	"_comment": "This config was generated using 'stryker init'. Please take a look at: https://stryker-mutator.io/docs/stryker-js/configuration/ for more information",
	"packageManager": "npm",
	
	"mutate": [
		"**/js/**/*.{jsx,tsx,ts,js}"
	],
	"reporters": [
		"html",
		"clear-text",
		"progress"
	],
	"testRunner": "jest",
	"coverageAnalysis": "perTest"
}
```

**Test runner config**

```
module.exports = {
    transform: {
        "^.+\\.(ts|tsx)$": "ts-jest",
        "^.+\\.(js|jsx)?$": "babel-jest",
    },
    clearMocks: true,
    verbose: true,
    testRegex: "(/__tests__/.*|(\\.|/)(test|spec))\\.(js|jsx|ts|tsx)?$",

    testEnvironment: 'jsdom',

    testPathIgnorePatterns: [
        "<rootDir>/node_modules/",
        "<rootDir>/upgrade/",
        "<rootDir>/vendor/",
    ],

    coverageReporters: ['clover', 'lcov', 'text'],


    collectCoverageFrom: [
        "**/plugins/**/*.{js,jsx,ts,tsx}",
        "**/src/**/*.{js,jsx,ts,tsx}",
        "**/js/**/*.{js,jsx,ts,tsx}",
        "**/webroot/**/*.{js,jsx,ts,tsx}",
        "**/js/**/*.stories.{js,jsx,ts,tsx}",
        "!**/js/dist/**",
        "!**/*.stories.*",
        "!**/js/bubbly/**",
        "!**/node_modules/**",
        "!**/vendor/**",
    ],


    setupFiles: [
        "<rootDir>/jest.setup.js"
    ],

    moduleNameMapper: {
        "\\.(css|less)$": "identity-obj-proxy",
    },

    // Module file extensions for importing
    moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"],

    transformIgnorePatterns: ["<rootDir>/node_modules/"],
};
```

**Stryker environment**

```
"@stryker-mutator/core": "^5.6.1",
"@stryker-mutator/jest-runner": "^5.6.1",
```

```
"jest": "^27.4.7",
```

**Test runner environment**

```shell
`stryker run`
`jest`
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 16
| npm              | 8
| Operating System | OSX

**Add stryker.log**

```
11:19:40 (16040) ERROR Stryker Unexpected error occurred while running Stryker SyntaxError: js/redux/slices/OrganizationsSlice.ts:82:16 expressionMutantPlacer could not place mutants with type(s): "OptionalChaining". Either remove this file from the list of files to be mutated, or exclude the mutator (using mutator.excludedMutations). Please report this issue at https://github.com/stryker-mutator/stryker-js/issues/new?assignees=&labels=%F0%9F%90%9B+Bug&template=bug_report.md&title=expressionMutantPlacer%20could%20not%20place%20mutants%20with%20type(s)%3A%20%22OptionalChaining%22. Original error: TypeError: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "ConditionalExpression"
    at Object.validate (/Users/myuser/PhpstormProjects/myproject/node_modules/@babel/types/lib/definitions/utils.js:131:11)
    at validateField (/Users/myuser/PhpstormProjects/myproject/node_modules/@babel/types/lib/validators/validate.js:24:9)
    at validate (/Users/myuser/PhpstormProjects/myproject/node_modules/@babel/types/lib/validators/validate.js:17:3)
    at NodePath._replaceWith (/Users/myuser/PhpstormProjects/myproject/node_modules/@babel/traverse/lib/path/replacement.js:170:5)
    at NodePath.replaceWith (/Users/myuser/PhpstormProjects/myproject/node_modules/@babel/traverse/lib/path/replacement.js:152:8)
    at Object.place (/Users/myuser/PhpstormProjects/myproject/node_modules/@stryker-mutator/instrumenter/dist/src/mutant-placers/expression-mutant-placer.js:102:14)
    at placeMutantsIfNeeded (/Users/myuser/PhpstormProjects/myproject/node_modules/@stryker-mutator/instrumenter/dist/src/transformers/babel-transformer.js:109:41)
    at exit (/Users/myuser/PhpstormProjects/myproject/node_modules/@stryker-mutator/instrumenter/dist/src/transformers/babel-transformer.js:54:13)
    at NodePath._call (/Users/myuser/PhpstormProjects/myproject/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/myuser/PhpstormProjects/myproject/node_modules/@babel/traverse/lib/path/context.js:36:14)
  80 |                 organizationsAdapter.upsertOne(state, organization);
  81 |
> 82 |                 state.stats[organization?.organization_id] = action.payload.stats;
     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  83 |                 state.current = organization;
  84 |                 state.loading = false;
  85 |                 return state;
    at File.buildCodeFrameError (/Users/myuser/PhpstormProjects/myproject/node_modules/@babel/core/lib/transformation/file/file.js:249:12)
    at NodePath.buildCodeFrameError (/Users/myuser/PhpstormProjects/myproject/node_modules/@babel/traverse/lib/path/index.js:139:21)
    at throwPlacementError (/Users/myuser/PhpstormProjects/myproject/node_modules/@stryker-mutator/instrumenter/dist/src/mutant-placers/throw-placement-error.js:18:31)
    at placeMutantsIfNeeded (/Users/myuser/PhpstormProjects/myproject/node_modules/@stryker-mutator/instrumenter/dist/src/transformers/babel-transformer.js:113:58)
    at exit (/Users/myuser/PhpstormProjects/myproject/node_modules/@stryker-mutator/instrumenter/dist/src/transformers/babel-transformer.js:54:13)
    at NodePath._call (/Users/myuser/PhpstormProjects/myproject/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/myuser/PhpstormProjects/myproject/node_modules/@babel/traverse/lib/path/context.js:36:14)
    at NodePath.visit (/Users/myuser/PhpstormProjects/myproject/node_modules/@babel/traverse/lib/path/context.js:109:8)
    at TraversalContext.visitQueue (/Users/myuser/PhpstormProjects/myproject/node_modules/@babel/traverse/lib/context.js:103:16)
    at TraversalContext.visitSingle (/Users/myuser/PhpstormProjects/myproject/node_modules/@babel/traverse/lib/context.js:77:19)
```

**Comment by nicojs** [comment]
Thanks for reporting this issue. Should be a pretty easy fix.

As a workaround, you can use [` // Stryker disable` syntax](https://stryker-mutator.io/docs/stryker-js/disable-mutants#using-a--stryker-disable-comment) to disable mutating this specific bit.

**Comment by nicojs** [comment]
Destale

**Comment by nicojs** [comment]
I think this was already fixed some time ago. I've added an integration test in #4170 for this specific case so it won't regress in the future.
