### ISSUE TITLE
Process checker crash in CI - mutant timeout

### ISSUE THREAD

**Issue by blephy** [stryker-mutator/stryker-js#3483]
**Question**

Hi,

Running stryker locally is working fine, but in circleci with a large docker resource (4CPU 8GB RAM), stryker is stdout a lot of warning (seems a lot of mutant are in timeout) : 

```bash
Mutation testing  [] 22% (elapsed: ~4m, remaining: ~14m) 391/1763 tested (0 survived, 129 timed out)Mutation testing  [] 22% (elapsed: ~4m, remaining: ~14m) 392/1763 tested (0 survived, 129 timed out)Mutation testing  [] 22% (elapsed: ~4m, remaining: ~14m) 393/1763 tested (0 survived, 130 timed out)Mutation testing  [] 22% (elapsed: ~4m, remaining: ~14m) 394/1763 tested (0 survived, 131 timed out)Mutation testing  [] 22% (elapsed: ~4m, remaining: ~14m) 395/1763 tested (0 survived, 131 timed out)Mutation testing  [] 22% (elapsed: ~4m, remaining: ~14m) 396/1763 tested (0 survived, 132 timed out)16:29:29 (160) WARN ChildProcessProxy Child process [pid 1773] exited unexpectedly with exit code null (SIGKILL). Stdout and stderr were empty. ChildProcessCrashedError: Child process [pid 1773] exited unexpectedly with exit code null (SIGKILL). Stdout and stderr were empty.
    at ChildProcessProxy.handleUnexpectedExit (/home/circleci/app/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:34:37)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:526:28)
    at Pipe.<anonymous> (node:net:687:12) {
  innerError: undefined,
  pid: 1773,
  exitCode: null,
  signal: 'SIGKILL'
}
16:29:29 (160) WARN CheckerRetryDecorator Checker process [1773] crashed with exit code null. Retrying in a new process. ChildProcessCrashedError: Child process [pid 1773] exited unexpectedly with exit code null (SIGKILL). Stdout and stderr were empty.
    at ChildProcessProxy.handleUnexpectedExit (/home/circleci/app/node_modules/@stryker-mutator/core/dist/src/child-proxy/child-process-proxy.js:34:37)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:526:28)
    at Pipe.<anonymous> (node:net:687:12) {
  innerError: undefined,
  pid: 1773,
  exitCode: null,
  signal: 'SIGKILL'
}
```

With debug

```bash
16:55:12 (5438) DEBUG JestTestRunner Running jest with --findRelatedTests flag. Set jest.enableFindRelatedTests to false to run all tests on every mutant.
Mutation testing  [] 34% (elapsed: ~5m, remaining: ~11m) 601/1763 tested (0 survived, 200 timed out)16:55:12 (158) DEBUG ChildProcessProxy Kill 5169
16:55:13 (158) DEBUG ChildProcessProxy Started ChildProcessTestRunnerWorker in child process 5537
16:55:13 (158) DEBUG ChildProcessProxy Kill 5186
Mutation testing  [] 34% (elapsed: ~5m, remaining: ~11m) 602/1763 tested (0 survived, 200 timed out)16:55:13 (158) DEBUG ChildProcessProxy Started ChildProcessTestRunnerWorker in child process 5544
Mutation testing  [] 34% (elapsed: ~5m, remaining: ~11m) 603/1763 tested (0 survived, 200 timed out)16:55:14 (158) DEBUG ChildProcessProxy Kill 5205
16:55:14 (158) DEBUG ChildProcessProxy Started ChildProcessTestRunnerWorker in child process 5561
16:55:14 (158) DEBUG TimeoutDecorator Timeout expired, restarting the process and reporting timeout
Mutation testing  [] 34% (elapsed: ~6m, remaining: ~11m) 604/1763 tested (0 survived, 200 timed out)16:55:14 (158) DEBUG TimeoutDecorator Starting timeout timer (10215 ms) for a test run
Mutation testing  [] 34% (elapsed: ~6m, remaining: ~11m) 605/1763 tested (0 survived, 201 timed out)16:55:10 (5471) DEBUG ChildProcessProxyWorker Changing current working directory for this process to /home/circleci/app/.stryker-tmp/sandbox1493119
16:55:10 (5471) DEBUG PluginLoader Loading @stryker-mutator/* from /home/circleci/app/node_modules/@stryker-mutator
16:55:10 (5471) DEBUG PluginLoader Loading plugin "/home/circleci/app/node_modules/@stryker-mutator/instrumenter" (matched with expression @stryker-mutator/*)
16:55:10 (5471) DEBUG PluginLoader Loading plugin "/home/circleci/app/node_modules/@stryker-mutator/jest-runner" (matched with expression @stryker-mutator/*)
16:55:10 (5471) DEBUG PluginLoader Loading plugin "/home/circleci/app/node_modules/@stryker-mutator/typescript-checker" (matched with expression @stryker-mutator/*)
16:55:10 (5471) DEBUG PluginLoader Loading plugins /home/circleci/app/node_modules/@stryker-mutator/instrumenter
16:55:12 (5471) DEBUG PluginLoader Loading plugins /home/circleci/app/node_modules/@stryker-mutator/jest-runner
16:55:12 (5471) DEBUG PluginLoader Loading plugins /home/circleci/app/node_modules/@stryker-mutator/typescript-checker
16:55:14 (5471) DEBUG PluginLoader Loading plugins /home/circleci/app/node_modules/@stryker-mutator/core/dist/src/reporters/index.js
16:55:14 (5471) DEBUG jestTestAdapterFactory Detected Jest version 27.5.1
```

**Stryker environment**

```
├─┬ @stryker-mutator/core@5.6.1
│ ├─┬ @stryker-mutator/api@5.6.1
│ ├─┬ @stryker-mutator/instrumenter@5.6.1
│ │ ├── @stryker-mutator/api@5.6.1 deduped
│ │ ├── @stryker-mutator/util@5.6.1 deduped
│ ├─┬ @stryker-mutator/util@5.6.1
├─┬ @stryker-mutator/jest-runner@5.6.1
│ ├── @stryker-mutator/api@5.6.1 deduped
│ ├── @stryker-mutator/util@5.6.1 deduped
├─┬ @stryker-mutator/typescript-checker@5.6.1
│ ├── @stryker-mutator/api@5.6.1 deduped
│ ├── @stryker-mutator/util@5.6.1 deduped
```

```
"jest": "^27.5.1",
"ts-jest": "^27.1.4",
"typescript": "^4.6.3"
```

**Additional context**

stryker config

```js
/**
 * @type {import('@stryker-mutator/api/core').StrykerOptions}
 */
module.exports = {
  mutate: ['./src/**/*.ts', '!./src/TypeGuard/**/*.ts'],
  ignorePatterns: [
    '**/node_modules/**',
    '**/.github/**',
    '**/.husky/**',
    '**/.circleci/**',
    '**/.yarn/**',
    '**/stats/**',
    '**/docs/**',
    '**/documentations/**',
    '**/reports/**',
    '**/coverage/**',
    '**/build/**',
    '**/dist/**',
    '**/lib/**',
  ],
  packageManager: 'yarn',
  reporters: ['html', 'clear-text', 'progress', 'json'],
  htmlReporter: {
    baseDir: 'reports/stryker',
  },
  jsonReporter: {
    fileName: 'reports/stryker/mutation.json',
  },
  clearTextReporter: { logTests: true },
  testRunner: 'jest',
  jest: {
    projectType: 'custom',
    configFile: 'jest.config.js',
    enableFindRelatedTests: true,
  },
  coverageAnalysis: 'perTest',
  checkers: ['typescript'],
  tsconfigFile: 'tsconfig.json',
  thresholds: { high: 80, low: 40, break: 20 },
};
```

jest config

```js
module.exports = {
  rootDir: '.',
  moduleFileExtensions: ['ts', 'js', 'json'],
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  preset: 'ts-jest',
  globals: {
    'ts-jest': {
      tsconfig: '<rootDir>/tsconfig.jest.json',
    },
  },
  reporters: [
    'default',
    [
      'jest-junit',
      {
        ancestorSeparator: ' › ',
        classNameTemplate: '{classname}',
        outputDirectory: './reports/junit',
        outputName: 'lifen-cda-parser-jest-junit.xml',
        suiteName: 'jest lifen-cda-parser tests',
        titleTemplate: '{title}',
        uniqueOutputName: 'false',
        usePathForSuiteName: 'true',
      },
    ],
  ],
  coverageReporters: ['text', 'html', 'lcov', 'json'],
  collectCoverageFrom: [
    '<rootDir>/src/**/*.ts',
    '!<rootDir>/src/TypeGuard/**/*.ts',
    '!**/node_modules/**',
  ],
  coveragePathIgnorePatterns: ['/node_modules/'],
  coverageDirectory: '<rootDir>/reports/jest',
  coverageThreshold: {
    global: {
      statements: 60,
    },
  },
  testEnvironment: 'node',
  testMatch: ['<rootDir>/**/*.{spec,test}.ts', '<rootDir>__tests__/**/*.{spec,test}.ts'],
  displayName: {
    name: 'lifen-cda-parser',
    color: 'blue',
  },
};
```

tsconfig

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "node",
    "lib": ["ESNext"],
    "allowJs": true,
    "checkJs": false,
    "pretty": true,
    "strict": true,
    "alwaysStrict": true,
    "strictNullChecks": true,
    "downlevelIteration": true,
    "preserveConstEnums": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "exactOptionalPropertyTypes": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitOverride": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "noUncheckedIndexedAccess": true,
    "noPropertyAccessFromIndexSignature": true,
    "noFallthroughCasesInSwitch": true,
    "strictBindCallApply": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": false,
    "useUnknownInCatchVariables": true,
    "forceConsistentCasingInFileNames": true,
    "allowSyntheticDefaultImports": true,
    "allowUnusedLabels": false,
    "allowUnreachableCode": false,
    "noEmit": true,
    "skipLibCheck": true,
    "declaration": false,
    "sourceMap": false
  },
  "exclude": [
    "**/node_modules/**",
    "**/.github/**",
    "**/.husky/**",
    "**/.circleci/**",
    "**/.dependabot/**",
    "**/stats/**",
    "**/docs/**",
    "**/documentations/**",
    "**/reports/**",
    "**/coverage/**",
    "**/build/**",
    "**/dist/**",
    "**/lib/**"
  ],
  "include": ["."]
}
```

**Comment by blephy** [comment]
Seems this is resolved by adding the flag `--concurrency 8`. Without it, stryker was running 17 checker process(es) and 17 test runner process(es), and this seems to be closely related to my issue.

Unfortunately, i lose a bit of running time process, is there any other solution ?

**Comment by nicojs** [comment]
Hi @blephy thanks for reporting and posting your workaround.

I'm personally unfamiliar with circleci, but apparently it provides 35 cores? 🤯... but then it doesn't let use all of them? Or some of them are busy?

By default, StrykerJS will try to use 100% of your machine. The way it does this is by creating `n-1` workers, where `n` is the number of available CPU cores. Unfortunately, it is very difficult (or impossible) to know if a process is getting CPU attention (process starvation). 

What solution would you advise is to implement?

Note: by default github actions for example only provide 2 cores, but in my experience, we are allowed to use both, without running risks of starvation.

**Comment by blephy** [comment]
Hi @nicojs 

Happy to see you again :)

Thanks for those reminders. Maybe this kind of problem can be explained in the stryker documentation FAQ ? I don't know if this is the only reason to have this kind of warning, but it should help other people to resolve it.

Yes, in circleci, you can chose the amount of CPU and RAM allocated to each container in a job, with the `resource_class` [keyword](https://circleci.com/docs/2.0/configuration-reference/#resourceclass). I did chose `large` value to decrease the time needed to run stryker on. But i don't know how many virtual core have physical core. Seems 35 yes :)

I did iterate with the `--concurrency` stryker option to get it working until it crash. And it begin to crash at `10`.

Additionally, it seems resource graph are the same between the use of `--concurrency` and not : 

**with concurrency 8 and large resource** 

<img width="1101" alt="Capture d’écran 2022-04-28 à 16 59 00" src="https://user-images.githubusercontent.com/24233935/165783733-a4bb6732-c6d4-4cd9-b842-69be94df60af.png">

**without concurrency and large resource** 

<img width="1096" alt="Capture d’écran 2022-04-28 à 17 00 23" src="https://user-images.githubusercontent.com/24233935/165783812-5d028400-aba7-4abf-9385-1efd47f5e367.png">

> note that without concurrency, with the same codebase, stryker is running with 4x more runner but is near to 4x more slower 😆 

Furthermore, circleci is experiencing some service degradation since days, and this is probably the reason.

I will try to not use `--concurrency` option and post here the result.

**Comment by blephy** [comment]
Circleci is now more fit, i did some test : 

- with `--concurrency 16`: bug persist.
- without `--concurrency` option: bug persist.

So i need to preserve `--concurrency 8` in order to get it working.

I don't know if it is from stryker resort, but it could be great to update the documentation about this issue in CI. Maybe just inform users to use this option if any trouble like this occurred.

Additionally, we maybe should investigate if the formula to calculate the number of runner fits with all physical / logical architecture. idk

**Comment by nicojs** [comment]
@blephy I think this is the underlying issue: https://circleci.canny.io/cloud-feature-requests/p/have-nproc-accurately-reporter-number-of-cpus-available-to-container

We should investigate getting the number of physical CPUs
