### ISSUE TITLE
Initial test run fails when mutating code related with angular module lazy loading

### ISSUE THREAD

**Issue by Zialus** [stryker-mutator/stryker-js#3657]
**Summary**

As a followup to https://github.com/stryker-mutator/stryker-js/issues/2736, I'm leaving a small reproducer example of the mentioned problem.

https://github.com/Zialus/angular-cnzrtw

```
➜  angular-cnzrtw git:(main) ✗ npm t

> angular.io-example@0.0.0 test
> ng test

✔ Browser application bundle generation complete.
28 07 2022 03:17:52.138:INFO [karma-server]: Karma v6.4.0 server started at http://localhost:9876/
28 07 2022 03:17:52.140:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
28 07 2022 03:17:52.149:INFO [launcher]: Starting browser ChromeHeadless
28 07 2022 03:17:53.358:INFO [Chrome Headless 103.0.5060.134 (Mac OS 10.15.7)]: Connected on socket lW5sqFcGnb9yNn3GAAAB with id 82348800
Chrome Headless 103.0.5060.134 (Mac OS 10.15.7): Executed 1 of 1 SUCCESS (0.031 secs / 0.027 secs)
TOTAL: 1 SUCCESS

=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
================================================================================
```

```
➜  angular-cnzrtw git:(main) ✗ npm run stryker

> angular.io-example@0.0.0 stryker
> stryker run

03:18:06 (16955) INFO ProjectReader Found 11 of 300 file(s) to be mutated.
03:18:06 (16955) INFO Instrumenter Instrumented 11 source file(s) with 25 mutant(s)
03:18:07 (16955) INFO ConcurrencyTokenProvider Creating 1 test runner process(es).
03:18:22 (16955) INFO DryRunExecutor Starting initial test run (karma test runner with "perTest" coverage analysis). This may take a while.
03:18:23 (16955) ERROR DryRunExecutor One or more tests failed in the initial test run:
	Router Module should navigate to view page
		Error: Cannot find module './customers/customers.module'
error properties: Object({ code: 'MODULE_NOT_FOUND' })
    at apply (src/app/ lazy namespace object:5:1)
    at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:372:26)
    at ProxyZoneSpec.onInvoke (node_modules/zone.js/fesm2015/zone-testing.js:287:39)
    at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:371:52)
    at Object.onInvoke (node_modules/@angular/core/fesm2020/core.mjs:26376:33)
    at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:371:52)
    at Zone.run (node_modules/zone.js/fesm2015/zone.js:134:43)
    at apply (node_modules/zone.js/fesm2015/zone.js:1275:36)
    at _ZoneDelegate.invokeTask (node_modules/zone.js/fesm2015/zone.js:406:31)
    at ProxyZoneSpec.onInvokeTask (node_modules/zone.js/fesm2015/zone-testing.js:318:39)
    at _ZoneDelegate.invokeTask (node_modules/zone.js/fesm2015/zone.js:405:60)
    at Object.onInvokeTask (node_modules/zone.js/fesm2015/zone.js:284:85)
    at _ZoneDelegate.invokeTask (node_modules/zone.js/fesm2015/zone.js:405:60)
    at Object.onInvokeTask (node_modules/@angular/core/fesm2020/core.mjs:26363:33)
    at _ZoneDelegate.invokeTask (node_modules/zone.js/fesm2015/zone.js:405:60)
    at Zone.runTask (node_modules/zone.js/fesm2015/zone.js:178:47)
    at drainMicroTaskQueue (node_modules/zone.js/fesm2015/zone.js:585:35)
03:18:23 (16955) ERROR Stryker There were failed tests in the initial test run.
➜  angular-cnzrtw git:(main) ✗
```

**Comment by nicojs** [comment]
@Zialus thanks for the clear bug report with reproduction example.

I think what is happening here is that the webpack plugin that is responsible for creating the different (lazy-loaded) js bundles per module can't handle the instrumented code by Stryker.

I think the way to fix it for all angular projects is with #3229 and then ignoring these mutants using heuristics.

In the meantime, there are 2 workarounds. We  can also add `"!src/**/*-routing.module.ts"` in the `mutate` property for the angular template.

<details>
<summary>Disable the mutants for the lines responsible for `loadChildren`</summary>

```diff
const routes: Routes = [
  {
    path: "customers",
+    // Stryker disable all
    loadChildren: () =>
      import("./customers/customers.module").then((m) => m.CustomersModule),
+    // Stryker enable all
  },
  {
    path: "orders",
+    // Stryker disable all
    loadChildren: () =>
      import("./orders/orders.module").then((m) => m.OrdersModule),
+    // Stryker enable all
  },
  {
    path: "",
    redirectTo: "",
    pathMatch: "full",
  },
];
```

</details>

<details>
<summary>Prevent the routing module from ever being mutated</summary>

```diff
// @ts-check
/** @type {import('@stryker-mutator/api/core').PartialStrykerOptions} */
const config = {
  _comment:
    "This config was generated using 'stryker init'. Please see the guide for more information: https://stryker-mutator.io/docs/stryker-js/guides/angular",
  mutate: [
    "src/**/*.ts",
    "!src/**/*.spec.ts",
    "!src/test.ts",
    "!src/environments/*.ts",
+    "!src/**/*-routing.module.ts"
  ],
  testRunner: "karma",
  karma: {
    configFile: "karma.conf.js",
    projectType: "angular-cli",
    config: {
      browsers: ["ChromeHeadless"],
    },
  },
  reporters: ["progress", "clear-text", "html"],
  concurrency: 1,
  concurrency_comment:
    "Recommended to use about half of your available cores when running stryker with angular",
  coverageAnalysis: "perTest",
};
export default config;
```

</details>

**Comment by rolivares** [comment]
the problem still happening, is this in a roadmap for this or I should just apply the workaround ?
