### ISSUE TITLE
Stryker fails with `create-react-app` and Jest 28/29

### ISSUE THREAD

**Issue by pinkfloydx33** [stryker-mutator/stryker-js#3783]
**Summary**

We've upgraded out application to React18 and Jest28. After upgrade, Stryker no longer runs and throws exceptions during initialization. This appears to happen with both Jest 28 and 29 alongside `create-react-app`.  Note that `npm test` and `react-scripts test` both run without issue. See notes at the bottom of the issue for some investigatory details.

> (5500) ERROR DryRunExecutor One or more tests resulted in an error:
>         undefined● Invalid return value:
>   `process()` or/and `processAsync()` method of code transformer found at
>   "C:/Development/My.App/node_modules/react-scripts/config/jest/fileTransform.js"
>   should return an object or a Promise resolving to an object. The object
>   must have `code` property with a string of processed code.
>   This error may be caused by a breaking change in Jest 28:
>   https://jestjs.io/docs/upgrading-to-jest28#transformer
>   Code Transformation Documentation:
>   https://jestjs.io/docs/code-transformation
>  Error: ● Invalid return value:
>   `process()` or/and `processAsync()` method of code transformer found at
>   "C:/Development/My.App/node_modules/react-scripts/config/jest/fileTransform.js"
>   should return an object or a Promise resolving to an object. The object
>   must have `code` property with a string of processed code.
>   This error may be caused by a breaking change in Jest 28:
>   https://jestjs.io/docs/upgrading-to-jest28#transformer
>   Code Transformation Documentation:
>   https://jestjs.io/docs/code-transformation
> 
>     at ScriptTransformer._buildTransformResult (C:\Development\My.App\node_modules\@jest\transform\build\ScriptTransformer.js:503:15)
>     at ScriptTransformer.transformSource (C:\Development\My.App\node_modules\@jest\transform\build\ScriptTransformer.js:624:17)
>     at ScriptTransformer._transformAndBuildScript (C:\Development\My.App\node_modules\@jest\transform\build\ScriptTransformer.js:757:40)
>     at ScriptTransformer.transform (C:\Development\My.App\node_modules\@jest\transform\build\ScriptTransformer.js:814:19)
>     at Runtime.transformFile (C:\Development\My.App\node_modules\jest-runtime\build\index.js:1627:47)
>     at Runtime._execModule (C:\Development\My.App\node_modules\jest-runtime\build\index.js:1544:34)
>     at Runtime._loadModule (C:\Development\My.App\node_modules\jest-runtime\build\index.js:1124:12)
>     at Runtime.requireModule (C:\Development\My.App\node_modules\jest-runtime\build\index.js:960:12)
>     at Runtime.requireModuleOrMock (C:\Development\My.App\node_modules\jest-runtime\build\index.js:1145:21)
>     at Object.<anonymous> (C:\Development\My.App\stryker-tmp\sandbox9096431\src\components\Nav\NavBar.tsx:68:1)
>     at Runtime._execModule (C:\Development\My.App\node_modules\jest-runtime\build\index.js:1596:24)
>     at Runtime._loadModule (C:\Development\My.App\node_modules\jest-runtime\build\index.js:1124:12)
>     at Runtime.requireModule (C:\Development\My.App\node_modules\jest-runtime\build\index.js:960:12)
>     at Runtime.requireModuleOrMock (C:\Development\My.App\node_modules\jest-runtime\build\index.js:1145:21)
>     at Object.<anonymous> (C:\Development\My.App\stryker-tmp\sandbox9096431\src\components\Nav\index.tsx:66:1)
>     at Runtime._execModule (C:\Development\My.App\node_modules\jest-runtime\build\index.js:1596:24)
>     at Runtime._loadModule (C:\Development\My.App\node_modules\jest-runtime\build\index.js:1124:12)
>     at Runtime.requireModule (C:\Development\My.App\node_modules\jest-runtime\build\index.js:960:12)
>     at Runtime.requireModuleOrMock (C:\Development\My.App\node_modules\jest-runtime\build\index.js:1145:21)
>     at Object.<anonymous> (C:\Development\My.App\stryker-tmp\sandbox9096431\src\components\Signup\Signup.test.tsx:4:1)
>     at Runtime._execModule (C:\Development\My.App\node_modules\jest-runtime\build\index.js:1596:24)
>     at Runtime._loadModule (C:\Development\My.App\node_modules\jest-runtime\build\index.js:1124:12)
>     at Runtime.requireModule (C:\Development\My.App\node_modules\jest-runtime\build\index.js:960:12)
>     at jestAdapter (C:\Development\My.App\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapter.js:89:13)
>     at runTestInternal (C:\Development\My.App\node_modules\jest-runner\build\runTest.js:407:16)
>     at runTest (C:\Development\My.App\node_modules\jest-runner\build\runTest.js:491:34)

**Stryker config**

```javascript
const config = {
  testRunner: "jest",
  mutator: {
    excludedMutations: [
      "StringLiteral",
      "ObjectLiteral",
      "BlockStatement"
    ]
  },
  reporters: [ "clear-text","progress" ],
  tsconfigFile: "tsconfig.json",
  tempDirName: "stryker-tmp",
  mutate: [
    "src/**/*.{ts,tsx,js,jsx}",
    "!src/**/*.{spec,test}.{ts,tsx,js,jsx}"
  ], 
  coverageAnalysis: "perTest",
  ignorePatterns: [
    "dist",
    "eng",
    "build",
    "reports",
    "results",
    "stryker-tmp"
  ],
  checkers: [
    "typescript"
  ],
  jest: {
    projectType: "create-react-app"
  }
};
export default config;
```

**Test runner config**
```json
  "jest": {
    "testMatch": [
      "<rootDir>/src/**/*.{test,spec}.{js,jsx,ts,tsx}"
    ],
    "collectCoverageFrom": [
      "<rootDir>/src/**/*.{js,jsx,ts,tsx}",
      "!<rootDir>/src/**/*.{test,spec}.{js,jsx,ts,tsx}",
      "!<rootDir>/src/types/**/*",
      "!<rootDir>/src/**/reportWebVitals.ts",
      "!<rootDir>/node_modules/",
      "!<rootDir>/*.js",
      "!**/__mocks__/**"
    ],
    "coverageReporters": [
      "clover",
      "json",
      "lcov",
      "text",
      "cobertura"
    ]
  }
```

**Stryker environment**

```
+-- @stryker-mutator/core@6.2.2
+-- @stryker-mutator/jest-runner@6.2.2
+-- @stryker-mutator/typescript-checker@6.2.2
```

```
+-- jest@29.1.2
+-- jest-environment-jsdom@29.1.2
+-- react-scripts@5.0.1
```

**Test runner environment**

```shell
# tests
react-scripts test

# stryker
stryker run stryker.conf.mjs
```

See above for jest configuration

**Your Environment**

| software               | version(s)                                |
| ------------------- | -------------------------------- |
| node                     | 16.16.0 (also verified 18.3.0)   |
| npm                      | 8.15.1                                      |
| Operating System | Windows 10 / Ubuntu 22.04  |

**Add stryker.log**
[stryker.log](https://github.com/stryker-mutator/stryker-js/files/9744989/stryker.log)

# Notes
Test runs **always** executed without issue. It's only during Stryker execution that these problems occur.

## jest-watch-typeahead
Initially after upgrading, Stryker was failing with the following error:

> ERROR DryRunExecutor One or more tests resulted in an error:
>         Test runner crashed. Tried twice to restart it without any luck. Last time the error message was: Error: : ● Validation Error:
> 
>   Watch plugin jest-watch-typeahead/filename cannot be found. Make sure the watchPlugins configuration option points to an existing node module.

After some Googling, it was found to be because of an outdated reference to `jest-watch-typeahead`; Adding a reference to the following package enabled Stryker to get further along in the process:

```
+-- jest-watch-typeahead@2.2.0
```

## Multiple Jests

After some investigation with @nicojs over the weekend, we (he) discovered that:
- I have multiple versions of Jest, and 
- Stryker is not resolving the correct version 

The output of `npm why jest`:

```
jest@29.1.2 dev
node_modules/jest
  dev jest@"^29.1.2" from the root project
  peer jest@"^27.0.0 || ^28.0.0 || ^29.0.0" from jest-watch-typeahead@2.2.0
  node_modules/jest-watch-typeahead
    dev jest-watch-typeahead@"^2.2.0" from the root project
  peer jest@"^29.0.0" from ts-jest@29.0.3
  node_modules/ts-jest
    dev ts-jest@"^29.0.3" from the root project

jest@27.5.1 dev
node_modules/react-scripts/node_modules/jest
  jest@"^27.4.3" from react-scripts@5.1.0-next.14
  node_modules/react-scripts
    dev react-scripts@"5.1.0-next.14" from the root project
  peer jest@"^27.0.0 || ^28.0.0" from jest-watch-typeahead@1.1.0
  node_modules/react-scripts/node_modules/jest-watch-typeahead
    jest-watch-typeahead@"^1.0.0" from react-scripts@5.1.0-next.14
    node_modules/react-scripts
      dev react-scripts@"5.1.0-next.14" from the root project
```

Version `27.5.1` is the one referenced by `react-scripts` and `29.1.2` is the version referenced directly via my `package.json` file. We discovered that Stryker is not loading the correct version. We manually modified the following files to force resolution of `jest` with respect to `react-scripts`:
- node_modules/@stryker-mutator/jest-runner/dist/src/utils/jest-wrapper.js
- node_modules/@stryker-mutator/jest-runner/dist/src/jest-plugins/cjs/import-jest-environment.js

This at least _appeared_ to correct the issue, allowing Stryker to run inside my environment.

**Comment by pinkfloydx33** [comment]
Note that there's an open issue to update the referenced version of Jest to 28+  [create-react-app#12444](https://github.com/facebook/create-react-app/issues/12444). There _is_ a PR that will close that issue; [create-react-app#12662](https://github.com/facebook/create-react-app/pull/12662) was created in August and updates to Jest@29. This would technically resolve the issue (for now) however I can see multiple Jests happening in the future when CRA gets behind again
