### ISSUE TITLE
`__dirname` in `node_modules` and mock-fs

### ISSUE THREAD

**Issue by regseb** [stryker-mutator/stryker-js#3978]
**Summary**

I think `__dirname` has the wrong value in the `node_modules` directory files.

In my unit tests, I use [mock-fs](https://www.npmjs.com/package/mock-fs) to mock the whole file system. But it doesn't work in some cases with Stryker.

Here is a _very simplified_ version of my test:

```Javascript
// test.js
import assert from "node:assert/strict";
import mock from "mock-fs";
import NpmPackageJsonLint from "npm-package-json-lint";

it("should return notices", async function () {
    mock({
        // Keep the "node_modules" directory because the
        // linter needs to access files in it.
        "node_modules/": mock.load("node_modules/"),
        "package.json": `{ "name": "FOO" }`,
    });

    const notices = await NpmPackageJsonLint.lint("package.json");
    assert.equal(notices.length, 2);
});
```

```JavaScript
// node_modules/npm-package-json-lint/index.js
export default class NpmPackageJsonLint {
    lint() {
        const rulesDirectory = path.join(__dirname, 'rules');
        const rules = readdirSync(rulesDirectory);
        // ...
        return notices;
    }
};
```

```
14:26:28 (44017) ERROR DryRunExecutor One or more tests failed in the initial test run:
	should return notices
		ENOENT: no such file or directory, scandir '/home/regseb/testcase/node_modules/npm-package-json-lint/rules'
14:26:29 (44017) ERROR Stryker There were failed tests in the initial test run.
```

I think mock-fs create the virtual directory in `/home/regseb/testcase/.stryker-tmp/sandbox3394431/node_modules`. But `__dirname` returns `/home/regseb/testcase/node_modules/npm-package-json-lint`.

Without mock-fs it works because the files are in both directories (`.stryker-tmp/sandbox3394431/node_modules` and `node_modules`). But it can be a problem if a dependency does `path.join(__dirname, "..", "..")` (which is very unlikely).

**Files to reproduce**

- **package.json**

  ```JSON
  {
    "name": "testcase",
    "version": "1.0.0",
    "dependencies": {
      "@stryker-mutator/core": "6.3.1",
      "@stryker-mutator/mocha-runner": "6.3.1",
      "mocha": "10.2.0",
      "mock-fs": "5.2.0"
    }
  }
  ```

- **stryker.conf.js**

  ```JavaScript
  module.exports = {
      mochaOptions: { spec: ["test.js"] },
      testRunner: "mocha",
  };
  ```

- **test.js**

  ```JavaScript
  const fs = require("node:fs");
  const mock = require("mock-fs");
  const foo = require("foo");

  it("shouldn't fail in stryker", async function () {
      mock({ "node_modules/": mock.load("node_modules/") });
      console.log(foo.bar());
      //console.log(fs.readdirSync(__dirname));
      mock.restore();
  });
  ```

- **foo/package.json** (fake dependency)

  ```JSON
  {
    "name": "foo",
    "version": "1.0.0"
  }
  ```

- **foo/index.js**

  ```JavaScript
  const fs = require("fs");

  module.exports = {
      bar() { return fs.readdirSync(__dirname); },
  };
  ```

**To reproduce**

Unzip [testcase.zip](https://github.com/stryker-mutator/stryker-js/files/10743613/testcase.zip).

```shell
cd testcase
npm i
cp -r foo node_modules
npx mocha test.js
npx stryker run --fileLogLevel trace
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | v18.14.0
| npm              | 9.4.2
| Operating System | Ubuntu 22.04.1 LTS

**Add stryker.log**

[stryker.log](https://github.com/stryker-mutator/stryker-js/files/10743636/stryker.log)

**Fix**

Perhaps by replacing the symbolic link of `node_modules` by a copy of the directory.

- Add `sendNodeModules` property in configuration:
  - `"symlink"` (default): replace [`{ symlinkNodeModules: true }`](https://stryker-mutator.io/docs/stryker-js/configuration/#symlinknodemodules-boolean)
  - `"copy"`: new! 🚀
  - `"none"`: replace `{ symlinkNodeModules: false }`
- Change [`symlinkNodeModulesIfNeeded()`](https://github.com/stryker-mutator/stryker-js/blob/fa2b77e3572884f44329e3f03b9201e9fd37082c/packages/core/src/sandbox/sandbox.ts#L100-L128) function:

```JavaScript
// packages/core/src/sandbox/sandbox.ts
export class Sandbox implements Disposable {
  // ...
  private async sendNodeModulesIfNeeded(): Promise<void> {
    this.log.debug('Start symlink node_modules');
    if (this.options.sendNodeModules !== "none" && !this.options.inPlace) {
      // TODO: Change with this.options.basePath when we have it
      const basePath = process.cwd();
      const nodeModulesList = await fileUtils.findNodeModulesList(basePath, this.options.tempDirName);

      if (nodeModulesList.length > 0) {
        const send = (this.options.sendNodeModules === "symlink"
            ? fileUtils.symlinkJunction
            : fileUtils.copyDirectoryRecursive);
        for (const nodeModules of nodeModulesList) {
          this.log.debug(`Symlink/Copy ${path.resolve(nodeModules)} to ${path.join(this.workingDirectory, nodeModules)}`);
          await send(path.resolve(nodeModules), path.join(this.workingDirectory, nodeModules))
            .catch((error: NodeJS.ErrnoException) => {
              if (error.code === 'EEXIST') {
                this.log.warn(
                  normalizeWhitespaces(`Could not symlink/copy "${nodeModules}" in sandbox directory,
              it is already created in the sandbox. Please remove the node_modules from your sandbox files.
              Alternatively, set \`sendNodeModules\` to \`"none"\` to disable this warning.`)
                );
              } else {
                this.log.warn(`Unexpected error while trying to symlink/copy "${nodeModules}" in sandbox directory.`, error);
              }
            });
        }
      } else {
        this.log.debug(`Could not find a node_modules folder to symlink/copy into the sandbox directory. Search "${basePath}" and its parent directories`);
      }
    }
  }
  // ...
}
```

```JavaScript
// packages/core/src/utils/file-utils.ts
export const fileUtils = {
  // ...
  /**
   * Asynchronously copies the entire directory structure from src to dest, including subdirectories and files.
   * @param src The source path to copy.
   * @param dest The destination path to copy to.
   * @see https://nodejs.org/api/fs.html#fspromisescpsrc-dest-options
   */
  async copyDirectoryRecursive(src: string, dest: string): Promise<void> {
    await fs.promises.mkdir(dest, { recursive: true });
    for (const file of await fs.promises.readdir(src)) {
      const srcFileName = path.join(src, file);
      const destFileName = path.join(dest, file);
      const stats = await fs.promises.lstat(srcFileName);
      if (stats.isFile()) {
        await fs.promises.copyFile(srcFileName, destFileName, fs.constants.COPYFILE_EXCL | fs.constants.COPYFILE_FICLONE);
      } else {
        await this.copyDirectoryRecursive(srcFileName, destFileName);
      }
    }
  },
  // ...
};
```

**Comment by nicojs** [comment]
Hi @regseb 👋

I think `mock-fs` might not be compatible with our default way of sandboxing the files. Could you try again using [`--inPlace`](https://stryker-mutator.io/docs/stryker-js/configuration/#inplace-boolean) mode?

**Comment by nicojs** [comment]
You're misusing `ignorePatterns` here, as you can override [`mochaOptions.spec`](https://stryker-mutator.io/docs/stryker-js/mocha-runner/#mochaoptionsspec-string-or-string). That should be the preferred way of selecting test files for the mocha plugin.

**Comment by regseb** [comment]
The files I put in `ignorePatterns` aren't tested. So there are no test files to exclude with the `mochaOptions.spec` option. I understand that this is not the goal of `ignorePatterns`, but I haven't found any other options for not testing certain files. For example for files that do not export any methods and are directly imported into the HTML pages.

---

Here is a test case:

- _src/_
  - _foo.js_: `module.exports = function foo() { return "foo"; };`
  - _bar.js_: `function bar() { return "bar"; };`
- _test/_
  - _foo.spec.js_:

    ```JavaScript
    const foo = require("../src/foo.js");

    it("foo()", function () {
        if (foo() !== "foo") throw new Error("Not foo");
    });
    ```

- _stryker.conf.js_:

  ```JavaScript
  module.exports = {
      mochaOptions: { spec: ["test/*.js"] },
      ignorePatterns: ["src/bar.js"],
      testRunner: "mocha",
  };
  ```

With this tree structure, I want to test only the _foo.js_ file. When I run `npx stryker run`:

```
INFO ProjectReader Found 1 of 8 file(s) to be mutated.
INFO Instrumenter Instrumented 1 source file(s) with 2 mutant(s)
INFO ...

All tests/foo.spec.js
  ✓ foo() (killed 2)

Ran 1.00 tests per mutant on average.
----------|---------|----------|-----------|------------|----------|----------|
File      | % score | # killed | # timeout | # survived | # no cov | # errors |
----------|---------|----------|-----------|------------|----------|----------|
All files |  100.00 |        2 |         0 |          0 |        0 |        0 |
 foo.js   |  100.00 |        2 |         0 |          0 |        0 |        0 |
----------|---------|----------|-----------|------------|----------|----------|
```

If I remove `ignorePatterns` from the configuration, the _bar.js_ file is tested (Stryker loses time to mutate it and it's reported in the dashboard).

```
INFO ProjectReader Found 2 of 9 file(s) to be mutated.
INFO Instrumenter Instrumented 2 source file(s) with 4 mutant(s)
INFO ...

All tests/foo.spec.js
  ✓ foo() (killed 2)

[NoCoverage] BlockStatement
src/bar.js:1:16
-   function bar() { return "bar"; };
+   function bar() {};

[NoCoverage] StringLiteral
src/bar.js:1:25
-   function bar() { return "bar"; };
+   function bar() { return ""; };

Ran 0.50 tests per mutant on average.
----------|---------|----------|-----------|------------|----------|----------|
File      | % score | # killed | # timeout | # survived | # no cov | # errors |
----------|---------|----------|-----------|------------|----------|----------|
All files |   50.00 |        2 |         0 |          0 |        2 |        0 |
 bar.js   |    0.00 |        0 |         0 |          0 |        2 |        0 |
 foo.js   |  100.00 |        2 |         0 |          0 |        0 |        0 |
----------|---------|----------|-----------|------------|----------|----------|
```

**Comment by nicojs** [comment]
Ah in that case I think it is [`mutate`](https://stryker-mutator.io/docs/stryker-js/configuration/#mutate-string) you're looking for.

**Comment by regseb** [comment]
Thanks for the `mutate` option. 👍

I found another problem with `inPlace`: file permissions aren't preserved. I have a file with permissions `-rwxr-xr-x` which loses the permission to execute: `-rw-rw-r--`. I tried to exclude the file (with `mutate`), but its permissions are still changed.

**Comment by nicojs** [comment]
Wow, you're on a roll 😅

This is an existing bug: #1463. 

> I tried to exclude the file (with `mutate`), but its permissions are still changed.

Stryker doesn't touch files that are not marked with `--mutate` when `--inPlace` is active. My best guess is that you've run with `--inPlace` once while mutating the `-rwxr-xr-x ` file. This overwrote the file with incorrect permissions. If you reset it by hand and try again (while not targeting this file with `mutate`) it should work 🤞. 

You can verify that you've reset the file correctly by running normal unit tests.

**Comment by regseb** [comment]
I created a minimal [testcase_rwx.zip](https://github.com/stryker-mutator/stryker-js/files/10817671/testcase_rwx.zip) to reproduce the permission problem: 🏄‍♂️

- _src/_
  - _foo.js_ (`-rw-rw-r--`): `module.exports = function foo() { return "foo"; };`
  - _bar.js_ (`-rwxr-xr-x`): `function bar() { return "bar"; };`
- _test/_
  - _foo.spec.js_:
    ```JavaScript
    const foo = require("../src/foo.js");

    it("foo()", function () {
        if (foo() !== "foo") throw new Error("Not foo");
    });
    ```
- _stryker.conf.js_:
  ```JavaScript
  module.exports = {
      inPlace: true,
      mochaOptions: { spec: ["test/*.js"] },
      mutate: ["src/foo.js"],
      testRunner: "mocha",
  };
  ```

To reproduce:

```Shell
ls -l src
npm install
npx stryker run
ls -l src
```

Result:

```Shell
$ ls -l src 
total 8
-rwxr-xr-x 1 regseb regseb 34 févr. 23 20:27 bar.js
-rw-rw-r-- 1 regseb regseb 51 févr. 23 20:27 foo.js

$ npm install

$ npx stryker run
20:48:33 (24790) INFO ProjectReader Found 1 of 6 file(s) to be mutated.
`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at Object.isModuleDeclaration (/home/regseb/tmp/testcase_rwx/node_modules/@babel/types/lib/validators/generated/index.js:3940:35)
    at isValidParent (file:///home/regseb/tmp/testcase_rwx/node_modules/@stryker-mutator/instrumenter/dist/src/mutators/string-literal-mutator.js:19:15)
20:48:33 (24790) INFO Instrumenter Instrumented 1 source file(s) with 2 mutant(s)
20:48:33 (24790) INFO ConcurrencyTokenProvider Creating 7 test runner process(es).
20:48:34 (24790) INFO Sandbox In place mode is enabled, Stryker will be overriding YOUR files. Find your backup at: .stryker-tmp/backup9822647
20:48:34 (24790) INFO DryRunExecutor Starting initial test run (mocha test runner with "perTest" coverage analysis). This may take a while.
20:48:34 (24790) INFO DryRunExecutor Initial test run succeeded. Ran 1 tests in 0 seconds (net 2 ms, overhead 68 ms).
Mutation testing  [] 50% (elapsed: <1m, remaining: n/a) 1/2 Mutants tested (0 surviveMutation testing  [] 100% (elapsed: <1m, remaining: n/a) 2/2 Mutants tested (0 survived, 0 timed out)

All tests/foo.spec.js
  ✓ foo() (killed 2)

Ran 1.00 tests per mutant on average.
----------|---------|----------|-----------|------------|----------|----------|
File      | % score | # killed | # timeout | # survived | # no cov | # errors |
----------|---------|----------|-----------|------------|----------|----------|
All files |  100.00 |        2 |         0 |          0 |        0 |        0 |
 foo.js   |  100.00 |        2 |         0 |          0 |        0 |        0 |
----------|---------|----------|-----------|------------|----------|----------|
20:48:34 (24790) INFO HtmlReporter Your report can be found at: file:///home/regseb/tmp/testcase_rwx/reports/mutation/mutation.html
20:48:34 (24790) INFO MutationTestExecutor Done in 1 second.
20:48:35 (24790) INFO Sandbox Resetting your original files from .stryker-tmp/backup9822647.

$ ls -l src      
total 8
-rw-rw-r-- 1 regseb regseb 34 févr. 23 20:48 bar.js
-rw-rw-r-- 1 regseb regseb 51 févr. 23 20:48 foo.js
```
