### ISSUE TITLE
False positive: Stryker changes the code in a way that the lines do not match anymore.

### ISSUE THREAD

**Issue by dominikzogg** [stryker-mutator/stryker-js#4370]
**Summary**

I've written a mocking library which i tested returning the line number if there is an error. Cause strkyer changes the line numbers with some mutations those mutations lead to errors, which they should not.

https://github.com/chubbyts/chubbyts-function-mock
https://github.com/chubbyts/chubbyts-function-mock/actions/runs/5535826437/jobs/10102653962

**Stryker config**

```json
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "testRunner": "jest",
  "coverageAnalysis": "off",
  "reporters": [
    "clear-text",
    "progress",
    "dashboard"
  ]
}
```

**Test runner config**

```json
{
    "preset": "ts-jest",
    "testEnvironment": "node",
    "collectCoverageFrom": [
      "src/**/*.ts"
    ],
    "coverageThreshold": {
      "global": {
        "lines": 100
      }
    }
  }
```

**Stryker environment**

```
@stryker-mutator/core@7.1.0
@stryker-mutator/jest-runner@7.1.0
```

```
@types/jest@29.5.3
jest@29.6.1
ts-jest@29.1.1
```

**Test runner environment**

```shell
npm run test
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | v18.16.1
| npm              | 9.7.2
| Operating System | Fedora Linux 38 (Workstation Edition) x86_64 

**Add stryker.log**

```
23:16:04 (31202) INFO ProjectReader Found 2 of 18 file(s) to be mutated.
23:16:04 (31202) INFO Instrumenter Instrumented 2 source file(s) with 134 mutant(s)
23:16:04 (31202) INFO ConcurrencyTokenProvider Creating 15 test runner process(es).
23:16:04 (31202) INFO DryRunExecutor Starting initial test run (jest test runner with "off" coverage analysis). This may take a while.
23:16:06 (31202) ERROR DryRunExecutor One or more tests failed in the initial test run:
        object-mock useObjectMock to less mocks
                Error: expect(received).toMatchInlineSnapshot(snapshot)

Snapshot name: `object-mock useObjectMock to less mocks 1`

Snapshot: [Error: Missing mock: {
  "line": "215",
  "mockIndex": 2
}]
Received: [Error: Missing mock: {
  "line": "216",
  "mockIndex": 2
}]
    at Object.<anonymous> (/home/<username>/Projects/chubbyts/chubbyts-function-mock/.stryker-tmp/sandbox6451457/tests/object-mock.test.ts:237:19)
    at Promise.then.completed (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/utils.js:300:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/utils.js:233:10)
    at _callCircusTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:314:40)
    at _runTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:250:3)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:125:9)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:120:9)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:120:9)
    at run (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:70:3)
    at runAndTransformResultsToJestFormat (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-runner/build/runTest.js:444:34)
        object-mock useObjectMock method name mismatch
                Error: expect(received).toMatchInlineSnapshot(snapshot)

Snapshot name: `object-mock useObjectMock method name mismatch 1`

Snapshot: [Error: Method name mismatch: {
  "line": "249",
  "mockIndex": 2,
  "actual": "substring",
  "expect": "uppercase"
}]
Received: [Error: Method name mismatch: {
  "line": "250",
  "mockIndex": 2,
  "actual": "substring",
  "expect": "uppercase"
}]
    at Object.<anonymous> (/home/<username>/Projects/chubbyts/chubbyts-function-mock/.stryker-tmp/sandbox6451457/tests/object-mock.test.ts:272:19)
    at Promise.then.completed (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/utils.js:300:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/utils.js:233:10)
    at _callCircusTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:314:40)
    at _runTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:250:3)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:125:9)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:120:9)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:120:9)
    at run (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:70:3)
    at runAndTransformResultsToJestFormat (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-runner/build/runTest.js:444:34)
        object-mock useObjectMock parameters count mismatch
                Error: expect(received).toMatchInlineSnapshot(snapshot)

Snapshot name: `object-mock useObjectMock parameters count mismatch 1`

Snapshot: [Error: Parameters count mismatch: {
  "line": "286",
  "mockIndex": 0,
  "name": "substring",
  "actual": 2,
  "expect": 3
}]
Received: [Error: Parameters count mismatch: {
  "line": "287",
  "mockIndex": 0,
  "name": "substring",
  "actual": 2,
  "expect": 3
}]
    at Object.<anonymous> (/home/<username>/Projects/chubbyts/chubbyts-function-mock/.stryker-tmp/sandbox6451457/tests/object-mock.test.ts:297:19)
    at Promise.then.completed (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/utils.js:300:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/utils.js:233:10)
    at _callCircusTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:314:40)
    at _runTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:250:3)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:125:9)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:120:9)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:120:9)
    at run (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:70:3)
    at runAndTransformResultsToJestFormat (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-runner/build/runTest.js:444:34)
        object-mock useObjectMock parameter mismatch
                Error: expect(received).toMatchInlineSnapshot(snapshot)

Snapshot name: `object-mock useObjectMock parameter mismatch 1`

Snapshot: [Error: Parameter mismatch: {
  "line": "312",
  "mockIndex": 1,
  "name": "substring",
  "parameterIndex": 2,
  "actual": 3,
  "expect": 2
}]
Received: [Error: Parameter mismatch: {
  "line": "313",
  "mockIndex": 1,
  "name": "substring",
  "parameterIndex": 2,
  "actual": 3,
  "expect": 2
}]
    at Object.<anonymous> (/home/<username>/Projects/chubbyts/chubbyts-function-mock/.stryker-tmp/sandbox6451457/tests/object-mock.test.ts:326:19)
    at Promise.then.completed (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/utils.js:300:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/utils.js:233:10)
    at _callCircusTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:314:40)
    at _runTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:250:3)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:125:9)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:120:9)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:120:9)
    at run (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:70:3)
    at runAndTransformResultsToJestFormat (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-runner/build/runTest.js:444:34), Error: expect(received).toMatchInlineSnapshot(snapshot)

Snapshot name: `object-mock useObjectMock parameter mismatch 2`

Snapshot: [Error: Parameter mismatch: {
  "line": "312",
  "mockIndex": 1,
  "name": "substring",
  "parameterIndex": 3,
  "actual": {
    "key": "value1"
  },
  "expect": {
    "key": "value1"
  }
}]
Received: [Error: Parameter mismatch: {
  "line": "313",
  "mockIndex": 1,
  "name": "substring",
  "parameterIndex": 3,
  "actual": {
    "key": "value1"
  },
  "expect": {
    "key": "value1"
  }
}]
    at Object.<anonymous> (/home/<username>/Projects/chubbyts/chubbyts-function-mock/.stryker-tmp/sandbox6451457/tests/object-mock.test.ts:342:19)
    at Promise.then.completed (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/utils.js:300:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/utils.js:233:10)
    at _callCircusTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:314:40)
    at _runTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:250:3)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:125:9)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:120:9)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:120:9)
    at run (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:70:3)
    at runAndTransformResultsToJestFormat (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-runner/build/runTest.js:444:34), Error: expect(received).toMatchInlineSnapshot(snapshot)

Snapshot name: `object-mock useObjectMock parameter mismatch 3`

Snapshot: [Error: Parameter mismatch: {
  "line": "312",
  "mockIndex": 1,
  "name": "substring",
  "parameterIndex": 3,
  "actual": {
    "key": "value2"
  },
  "expect": {
    "key": "value1"
  }
}]
Received: [Error: Parameter mismatch: {
  "line": "313",
  "mockIndex": 1,
  "name": "substring",
  "parameterIndex": 3,
  "actual": {
    "key": "value2"
  },
  "expect": {
    "key": "value1"
  }
}]
    at Object.<anonymous> (/home/<username>/Projects/chubbyts/chubbyts-function-mock/.stryker-tmp/sandbox6451457/tests/object-mock.test.ts:362:19)
    at Promise.then.completed (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/utils.js:300:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/utils.js:233:10)
    at _callCircusTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:314:40)
    at _runTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:250:3)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:125:9)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:120:9)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:120:9)
    at run (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:70:3)
    at runAndTransformResultsToJestFormat (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-runner/build/runTest.js:444:34)
        function-mock useFunctionMock to less mocks
                Error: expect(received).toMatchInlineSnapshot(snapshot)

Snapshot name: `function-mock useFunctionMock to less mocks 1`

Snapshot: [Error: Missing mock: {
  "line": "146",
  "mockIndex": 3
}]
Received: [Error: Missing mock: {
  "line": "147",
  "mockIndex": 3
}]
    at Object.<anonymous> (/home/<username>/Projects/chubbyts/chubbyts-function-mock/.stryker-tmp/sandbox6451457/tests/function-mock.test.ts:175:19)
    at Promise.then.completed (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/utils.js:300:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/utils.js:233:10)
    at _callCircusTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:314:40)
    at _runTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:250:3)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:125:9)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:120:9)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:120:9)
    at run (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:70:3)
    at runAndTransformResultsToJestFormat (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-runner/build/runTest.js:444:34)
        function-mock useFunctionMock parameters count mismatch
                Error: expect(received).toMatchInlineSnapshot(snapshot)

Snapshot name: `function-mock useFunctionMock parameters count mismatch 1`

Snapshot: [Error: Parameters count mismatch: {
  "line": "187",
  "mockIndex": 0,
  "actual": 2,
  "expect": 3
}]
Received: [Error: Parameters count mismatch: {
  "line": "188",
  "mockIndex": 0,
  "actual": 2,
  "expect": 3
}]
    at Object.<anonymous> (/home/<username>/Projects/chubbyts/chubbyts-function-mock/.stryker-tmp/sandbox6451457/tests/function-mock.test.ts:196:19)
    at Promise.then.completed (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/utils.js:300:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/utils.js:233:10)
    at _callCircusTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:314:40)
    at _runTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:250:3)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:125:9)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:120:9)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:120:9)
    at run (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:70:3)
    at runAndTransformResultsToJestFormat (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-runner/build/runTest.js:444:34)
        function-mock useFunctionMock parameter mismatch
                Error: expect(received).toMatchInlineSnapshot(snapshot)

Snapshot name: `function-mock useFunctionMock parameter mismatch 1`

Snapshot: [Error: Parameter mismatch: {
  "line": "210",
  "mockIndex": 0,
  "parameterIndex": 2,
  "actual": 3,
  "expect": 2
}]
Received: [Error: Parameter mismatch: {
  "line": "211",
  "mockIndex": 0,
  "parameterIndex": 2,
  "actual": 3,
  "expect": 2
}]
    at Object.<anonymous> (/home/<username>/Projects/chubbyts/chubbyts-function-mock/.stryker-tmp/sandbox6451457/tests/function-mock.test.ts:221:19)
    at Promise.then.completed (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/utils.js:300:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/utils.js:233:10)
    at _callCircusTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:314:40)
    at _runTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:250:3)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:125:9)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:120:9)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:120:9)
    at run (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:70:3)
    at runAndTransformResultsToJestFormat (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-runner/build/runTest.js:444:34), Error: expect(received).toMatchInlineSnapshot(snapshot)

Snapshot name: `function-mock useFunctionMock parameter mismatch 2`

Snapshot: [Error: Parameter mismatch: {
  "line": "210",
  "mockIndex": 0,
  "parameterIndex": 3,
  "actual": {
    "key": "value1"
  },
  "expect": {
    "key": "value1"
  }
}]
Received: [Error: Parameter mismatch: {
  "line": "211",
  "mockIndex": 0,
  "parameterIndex": 3,
  "actual": {
    "key": "value1"
  },
  "expect": {
    "key": "value1"
  }
}]
    at Object.<anonymous> (/home/<username>/Projects/chubbyts/chubbyts-function-mock/.stryker-tmp/sandbox6451457/tests/function-mock.test.ts:236:19)
    at Promise.then.completed (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/utils.js:300:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/utils.js:233:10)
    at _callCircusTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:314:40)
    at _runTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:250:3)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:125:9)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:120:9)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:120:9)
    at run (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:70:3)
    at runAndTransformResultsToJestFormat (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-runner/build/runTest.js:444:34), Error: expect(received).toMatchInlineSnapshot(snapshot)

Snapshot name: `function-mock useFunctionMock parameter mismatch 3`

Snapshot: [Error: Parameter mismatch: {
  "line": "210",
  "mockIndex": 0,
  "parameterIndex": 3,
  "actual": {
    "key": "value2"
  },
  "expect": {
    "key": "value1"
  }
}]
Received: [Error: Parameter mismatch: {
  "line": "211",
  "mockIndex": 0,
  "parameterIndex": 3,
  "actual": {
    "key": "value2"
  },
  "expect": {
    "key": "value1"
  }
}]
    at Object.<anonymous> (/home/<username>/Projects/chubbyts/chubbyts-function-mock/.stryker-tmp/sandbox6451457/tests/function-mock.test.ts:255:19)
    at Promise.then.completed (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/utils.js:300:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/utils.js:233:10)
    at _callCircusTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:314:40)
    at _runTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:250:3)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:125:9)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:120:9)
    at _runTestsForDescribeBlock (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:120:9)
    at run (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/run.js:70:3)
    at runAndTransformResultsToJestFormat (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/home/<username>/Projects/chubbyts/chubbyts-function-mock/node_modules/jest-runner/build/runTest.js:444:34)
23:16:06 (31202) ERROR Stryker There were failed tests in the initial test run.
```

**Comment by nicojs** [comment]
The problem is that Stryker will disable type checks by default, as in: TypeScript type checks. It does this, is by adding `// @ts-nocheck` atop each source file (it's the only way).  Also atop your tests files, causing an off-by-one error with your inline source maps (that are depend on your exact line).

You can disable this using: `"disableTypeChecks": "src/**/*.{js,ts,jsx,tsx,html,vue,cts,mts}"`. This will only disable type checks for your source files. Which is needed, because `ts-jest` will run type checking.

**Comment by dominikzogg** [comment]
@nicojs thanks for your response, based on it i created this: https://github.com/chubbyts/chubbyts-function-mock/commit/94a884a44960d9df8157167905507f58bc48298b#diff-25e7d881d0d5f1db55623160306770a86278dd832f3ce6ae5d5467f1c39d7783R6

**Comment by dominikzogg** [comment]
@nicojs the reason why it did not work on my first try was instead of `"disableTypeChecks": "src/**/*.{js,ts}"` i added `"disableTypeChecks": "src/**/*.{ts}"`. It works now, thank you
